/*
Drip Backend

Drip backend service.

API version: 1.0.0
Contact: dcafmocha@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drip

import (
	"encoding/json"
)

// ListProtoConfigsInner struct for ListProtoConfigsInner
type ListProtoConfigsInner struct {
	Pubkey string `json:"pubkey"`
	Granularity int32 `json:"granularity"`
	TriggerDcaSpread int32 `json:"triggerDcaSpread"`
	BaseWithdrawalSpread int32 `json:"baseWithdrawalSpread"`
}

// NewListProtoConfigsInner instantiates a new ListProtoConfigsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListProtoConfigsInner(pubkey string, granularity int32, triggerDcaSpread int32, baseWithdrawalSpread int32) *ListProtoConfigsInner {
	this := ListProtoConfigsInner{}
	this.Pubkey = pubkey
	this.Granularity = granularity
	this.TriggerDcaSpread = triggerDcaSpread
	this.BaseWithdrawalSpread = baseWithdrawalSpread
	return &this
}

// NewListProtoConfigsInnerWithDefaults instantiates a new ListProtoConfigsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListProtoConfigsInnerWithDefaults() *ListProtoConfigsInner {
	this := ListProtoConfigsInner{}
	return &this
}

// GetPubkey returns the Pubkey field value
func (o *ListProtoConfigsInner) GetPubkey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value
// and a boolean to check if the value has been set.
func (o *ListProtoConfigsInner) GetPubkeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pubkey, true
}

// SetPubkey sets field value
func (o *ListProtoConfigsInner) SetPubkey(v string) {
	o.Pubkey = v
}

// GetGranularity returns the Granularity field value
func (o *ListProtoConfigsInner) GetGranularity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Granularity
}

// GetGranularityOk returns a tuple with the Granularity field value
// and a boolean to check if the value has been set.
func (o *ListProtoConfigsInner) GetGranularityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Granularity, true
}

// SetGranularity sets field value
func (o *ListProtoConfigsInner) SetGranularity(v int32) {
	o.Granularity = v
}

// GetTriggerDcaSpread returns the TriggerDcaSpread field value
func (o *ListProtoConfigsInner) GetTriggerDcaSpread() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TriggerDcaSpread
}

// GetTriggerDcaSpreadOk returns a tuple with the TriggerDcaSpread field value
// and a boolean to check if the value has been set.
func (o *ListProtoConfigsInner) GetTriggerDcaSpreadOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TriggerDcaSpread, true
}

// SetTriggerDcaSpread sets field value
func (o *ListProtoConfigsInner) SetTriggerDcaSpread(v int32) {
	o.TriggerDcaSpread = v
}

// GetBaseWithdrawalSpread returns the BaseWithdrawalSpread field value
func (o *ListProtoConfigsInner) GetBaseWithdrawalSpread() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BaseWithdrawalSpread
}

// GetBaseWithdrawalSpreadOk returns a tuple with the BaseWithdrawalSpread field value
// and a boolean to check if the value has been set.
func (o *ListProtoConfigsInner) GetBaseWithdrawalSpreadOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseWithdrawalSpread, true
}

// SetBaseWithdrawalSpread sets field value
func (o *ListProtoConfigsInner) SetBaseWithdrawalSpread(v int32) {
	o.BaseWithdrawalSpread = v
}

func (o ListProtoConfigsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pubkey"] = o.Pubkey
	}
	if true {
		toSerialize["granularity"] = o.Granularity
	}
	if true {
		toSerialize["triggerDcaSpread"] = o.TriggerDcaSpread
	}
	if true {
		toSerialize["baseWithdrawalSpread"] = o.BaseWithdrawalSpread
	}
	return json.Marshal(toSerialize)
}

type NullableListProtoConfigsInner struct {
	value *ListProtoConfigsInner
	isSet bool
}

func (v NullableListProtoConfigsInner) Get() *ListProtoConfigsInner {
	return v.value
}

func (v *NullableListProtoConfigsInner) Set(val *ListProtoConfigsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListProtoConfigsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListProtoConfigsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListProtoConfigsInner(val *ListProtoConfigsInner) *NullableListProtoConfigsInner {
	return &NullableListProtoConfigsInner{value: val, isSet: true}
}

func (v NullableListProtoConfigsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListProtoConfigsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


