/*
Drip Backend

Drip backend service. All API's have a IP rate limit of 10 requests per second. 

API version: 1.0.0
Contact: mocha@dcaf.so
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drip

import (
	"encoding/json"
)

// SwapConfig struct for SwapConfig
type SwapConfig struct {
	Vault string `json:"vault"`
	VaultProtoConfig string `json:"vaultProtoConfig"`
	VaultTokenAAccount string `json:"vaultTokenAAccount"`
	VaultTokenBAccount string `json:"vaultTokenBAccount"`
	TokenAMint string `json:"tokenAMint"`
	TokenBMint string `json:"tokenBMint"`
	SwapTokenMint string `json:"swapTokenMint"`
	SwapTokenAAccount string `json:"swapTokenAAccount"`
	SwapTokenBAccount string `json:"swapTokenBAccount"`
	SwapFeeAccount string `json:"swapFeeAccount"`
	SwapAuthority string `json:"swapAuthority"`
	Swap string `json:"swap"`
}

// NewSwapConfig instantiates a new SwapConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSwapConfig(vault string, vaultProtoConfig string, vaultTokenAAccount string, vaultTokenBAccount string, tokenAMint string, tokenBMint string, swapTokenMint string, swapTokenAAccount string, swapTokenBAccount string, swapFeeAccount string, swapAuthority string, swap string) *SwapConfig {
	this := SwapConfig{}
	this.Vault = vault
	this.VaultProtoConfig = vaultProtoConfig
	this.VaultTokenAAccount = vaultTokenAAccount
	this.VaultTokenBAccount = vaultTokenBAccount
	this.TokenAMint = tokenAMint
	this.TokenBMint = tokenBMint
	this.SwapTokenMint = swapTokenMint
	this.SwapTokenAAccount = swapTokenAAccount
	this.SwapTokenBAccount = swapTokenBAccount
	this.SwapFeeAccount = swapFeeAccount
	this.SwapAuthority = swapAuthority
	this.Swap = swap
	return &this
}

// NewSwapConfigWithDefaults instantiates a new SwapConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSwapConfigWithDefaults() *SwapConfig {
	this := SwapConfig{}
	return &this
}

// GetVault returns the Vault field value
func (o *SwapConfig) GetVault() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vault
}

// GetVaultOk returns a tuple with the Vault field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetVaultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vault, true
}

// SetVault sets field value
func (o *SwapConfig) SetVault(v string) {
	o.Vault = v
}

// GetVaultProtoConfig returns the VaultProtoConfig field value
func (o *SwapConfig) GetVaultProtoConfig() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VaultProtoConfig
}

// GetVaultProtoConfigOk returns a tuple with the VaultProtoConfig field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetVaultProtoConfigOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VaultProtoConfig, true
}

// SetVaultProtoConfig sets field value
func (o *SwapConfig) SetVaultProtoConfig(v string) {
	o.VaultProtoConfig = v
}

// GetVaultTokenAAccount returns the VaultTokenAAccount field value
func (o *SwapConfig) GetVaultTokenAAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VaultTokenAAccount
}

// GetVaultTokenAAccountOk returns a tuple with the VaultTokenAAccount field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetVaultTokenAAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VaultTokenAAccount, true
}

// SetVaultTokenAAccount sets field value
func (o *SwapConfig) SetVaultTokenAAccount(v string) {
	o.VaultTokenAAccount = v
}

// GetVaultTokenBAccount returns the VaultTokenBAccount field value
func (o *SwapConfig) GetVaultTokenBAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VaultTokenBAccount
}

// GetVaultTokenBAccountOk returns a tuple with the VaultTokenBAccount field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetVaultTokenBAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VaultTokenBAccount, true
}

// SetVaultTokenBAccount sets field value
func (o *SwapConfig) SetVaultTokenBAccount(v string) {
	o.VaultTokenBAccount = v
}

// GetTokenAMint returns the TokenAMint field value
func (o *SwapConfig) GetTokenAMint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenAMint
}

// GetTokenAMintOk returns a tuple with the TokenAMint field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetTokenAMintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenAMint, true
}

// SetTokenAMint sets field value
func (o *SwapConfig) SetTokenAMint(v string) {
	o.TokenAMint = v
}

// GetTokenBMint returns the TokenBMint field value
func (o *SwapConfig) GetTokenBMint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenBMint
}

// GetTokenBMintOk returns a tuple with the TokenBMint field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetTokenBMintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenBMint, true
}

// SetTokenBMint sets field value
func (o *SwapConfig) SetTokenBMint(v string) {
	o.TokenBMint = v
}

// GetSwapTokenMint returns the SwapTokenMint field value
func (o *SwapConfig) GetSwapTokenMint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SwapTokenMint
}

// GetSwapTokenMintOk returns a tuple with the SwapTokenMint field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetSwapTokenMintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SwapTokenMint, true
}

// SetSwapTokenMint sets field value
func (o *SwapConfig) SetSwapTokenMint(v string) {
	o.SwapTokenMint = v
}

// GetSwapTokenAAccount returns the SwapTokenAAccount field value
func (o *SwapConfig) GetSwapTokenAAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SwapTokenAAccount
}

// GetSwapTokenAAccountOk returns a tuple with the SwapTokenAAccount field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetSwapTokenAAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SwapTokenAAccount, true
}

// SetSwapTokenAAccount sets field value
func (o *SwapConfig) SetSwapTokenAAccount(v string) {
	o.SwapTokenAAccount = v
}

// GetSwapTokenBAccount returns the SwapTokenBAccount field value
func (o *SwapConfig) GetSwapTokenBAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SwapTokenBAccount
}

// GetSwapTokenBAccountOk returns a tuple with the SwapTokenBAccount field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetSwapTokenBAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SwapTokenBAccount, true
}

// SetSwapTokenBAccount sets field value
func (o *SwapConfig) SetSwapTokenBAccount(v string) {
	o.SwapTokenBAccount = v
}

// GetSwapFeeAccount returns the SwapFeeAccount field value
func (o *SwapConfig) GetSwapFeeAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SwapFeeAccount
}

// GetSwapFeeAccountOk returns a tuple with the SwapFeeAccount field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetSwapFeeAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SwapFeeAccount, true
}

// SetSwapFeeAccount sets field value
func (o *SwapConfig) SetSwapFeeAccount(v string) {
	o.SwapFeeAccount = v
}

// GetSwapAuthority returns the SwapAuthority field value
func (o *SwapConfig) GetSwapAuthority() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SwapAuthority
}

// GetSwapAuthorityOk returns a tuple with the SwapAuthority field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetSwapAuthorityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SwapAuthority, true
}

// SetSwapAuthority sets field value
func (o *SwapConfig) SetSwapAuthority(v string) {
	o.SwapAuthority = v
}

// GetSwap returns the Swap field value
func (o *SwapConfig) GetSwap() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Swap
}

// GetSwapOk returns a tuple with the Swap field value
// and a boolean to check if the value has been set.
func (o *SwapConfig) GetSwapOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Swap, true
}

// SetSwap sets field value
func (o *SwapConfig) SetSwap(v string) {
	o.Swap = v
}

func (o SwapConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["vault"] = o.Vault
	}
	if true {
		toSerialize["vaultProtoConfig"] = o.VaultProtoConfig
	}
	if true {
		toSerialize["vaultTokenAAccount"] = o.VaultTokenAAccount
	}
	if true {
		toSerialize["vaultTokenBAccount"] = o.VaultTokenBAccount
	}
	if true {
		toSerialize["tokenAMint"] = o.TokenAMint
	}
	if true {
		toSerialize["tokenBMint"] = o.TokenBMint
	}
	if true {
		toSerialize["swapTokenMint"] = o.SwapTokenMint
	}
	if true {
		toSerialize["swapTokenAAccount"] = o.SwapTokenAAccount
	}
	if true {
		toSerialize["swapTokenBAccount"] = o.SwapTokenBAccount
	}
	if true {
		toSerialize["swapFeeAccount"] = o.SwapFeeAccount
	}
	if true {
		toSerialize["swapAuthority"] = o.SwapAuthority
	}
	if true {
		toSerialize["swap"] = o.Swap
	}
	return json.Marshal(toSerialize)
}

type NullableSwapConfig struct {
	value *SwapConfig
	isSet bool
}

func (v NullableSwapConfig) Get() *SwapConfig {
	return v.value
}

func (v *NullableSwapConfig) Set(val *SwapConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableSwapConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableSwapConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwapConfig(val *SwapConfig) *NullableSwapConfig {
	return &NullableSwapConfig{value: val, isSet: true}
}

func (v NullableSwapConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwapConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


