/*
Drip Backend

Drip backend service. All API's have a IP rate limit of 10 requests per second. 

API version: 1.0.0
Contact: mocha@dcaf.so
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drip

import (
	"encoding/json"
)

// Vault struct for Vault
type Vault struct {
	Pubkey string `json:"pubkey"`
	ProtoConfig string `json:"protoConfig"`
	TokenAAccount string `json:"tokenAAccount"`
	TokenBAccount string `json:"tokenBAccount"`
	TreasuryTokenBAccount string `json:"treasuryTokenBAccount"`
	TokenAMint string `json:"tokenAMint"`
	TokenBMint string `json:"tokenBMint"`
	LastDcaPeriod string `json:"lastDcaPeriod"`
	DripAmount string `json:"dripAmount"`
	// unix timestamp
	DcaActivationTimestamp string `json:"dcaActivationTimestamp"`
	Enabled bool `json:"enabled"`
}

// NewVault instantiates a new Vault object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVault(pubkey string, protoConfig string, tokenAAccount string, tokenBAccount string, treasuryTokenBAccount string, tokenAMint string, tokenBMint string, lastDcaPeriod string, dripAmount string, dcaActivationTimestamp string, enabled bool) *Vault {
	this := Vault{}
	this.Pubkey = pubkey
	this.ProtoConfig = protoConfig
	this.TokenAAccount = tokenAAccount
	this.TokenBAccount = tokenBAccount
	this.TreasuryTokenBAccount = treasuryTokenBAccount
	this.TokenAMint = tokenAMint
	this.TokenBMint = tokenBMint
	this.LastDcaPeriod = lastDcaPeriod
	this.DripAmount = dripAmount
	this.DcaActivationTimestamp = dcaActivationTimestamp
	this.Enabled = enabled
	return &this
}

// NewVaultWithDefaults instantiates a new Vault object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVaultWithDefaults() *Vault {
	this := Vault{}
	return &this
}

// GetPubkey returns the Pubkey field value
func (o *Vault) GetPubkey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value
// and a boolean to check if the value has been set.
func (o *Vault) GetPubkeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pubkey, true
}

// SetPubkey sets field value
func (o *Vault) SetPubkey(v string) {
	o.Pubkey = v
}

// GetProtoConfig returns the ProtoConfig field value
func (o *Vault) GetProtoConfig() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProtoConfig
}

// GetProtoConfigOk returns a tuple with the ProtoConfig field value
// and a boolean to check if the value has been set.
func (o *Vault) GetProtoConfigOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtoConfig, true
}

// SetProtoConfig sets field value
func (o *Vault) SetProtoConfig(v string) {
	o.ProtoConfig = v
}

// GetTokenAAccount returns the TokenAAccount field value
func (o *Vault) GetTokenAAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenAAccount
}

// GetTokenAAccountOk returns a tuple with the TokenAAccount field value
// and a boolean to check if the value has been set.
func (o *Vault) GetTokenAAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenAAccount, true
}

// SetTokenAAccount sets field value
func (o *Vault) SetTokenAAccount(v string) {
	o.TokenAAccount = v
}

// GetTokenBAccount returns the TokenBAccount field value
func (o *Vault) GetTokenBAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenBAccount
}

// GetTokenBAccountOk returns a tuple with the TokenBAccount field value
// and a boolean to check if the value has been set.
func (o *Vault) GetTokenBAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenBAccount, true
}

// SetTokenBAccount sets field value
func (o *Vault) SetTokenBAccount(v string) {
	o.TokenBAccount = v
}

// GetTreasuryTokenBAccount returns the TreasuryTokenBAccount field value
func (o *Vault) GetTreasuryTokenBAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TreasuryTokenBAccount
}

// GetTreasuryTokenBAccountOk returns a tuple with the TreasuryTokenBAccount field value
// and a boolean to check if the value has been set.
func (o *Vault) GetTreasuryTokenBAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TreasuryTokenBAccount, true
}

// SetTreasuryTokenBAccount sets field value
func (o *Vault) SetTreasuryTokenBAccount(v string) {
	o.TreasuryTokenBAccount = v
}

// GetTokenAMint returns the TokenAMint field value
func (o *Vault) GetTokenAMint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenAMint
}

// GetTokenAMintOk returns a tuple with the TokenAMint field value
// and a boolean to check if the value has been set.
func (o *Vault) GetTokenAMintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenAMint, true
}

// SetTokenAMint sets field value
func (o *Vault) SetTokenAMint(v string) {
	o.TokenAMint = v
}

// GetTokenBMint returns the TokenBMint field value
func (o *Vault) GetTokenBMint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenBMint
}

// GetTokenBMintOk returns a tuple with the TokenBMint field value
// and a boolean to check if the value has been set.
func (o *Vault) GetTokenBMintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenBMint, true
}

// SetTokenBMint sets field value
func (o *Vault) SetTokenBMint(v string) {
	o.TokenBMint = v
}

// GetLastDcaPeriod returns the LastDcaPeriod field value
func (o *Vault) GetLastDcaPeriod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastDcaPeriod
}

// GetLastDcaPeriodOk returns a tuple with the LastDcaPeriod field value
// and a boolean to check if the value has been set.
func (o *Vault) GetLastDcaPeriodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastDcaPeriod, true
}

// SetLastDcaPeriod sets field value
func (o *Vault) SetLastDcaPeriod(v string) {
	o.LastDcaPeriod = v
}

// GetDripAmount returns the DripAmount field value
func (o *Vault) GetDripAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DripAmount
}

// GetDripAmountOk returns a tuple with the DripAmount field value
// and a boolean to check if the value has been set.
func (o *Vault) GetDripAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DripAmount, true
}

// SetDripAmount sets field value
func (o *Vault) SetDripAmount(v string) {
	o.DripAmount = v
}

// GetDcaActivationTimestamp returns the DcaActivationTimestamp field value
func (o *Vault) GetDcaActivationTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DcaActivationTimestamp
}

// GetDcaActivationTimestampOk returns a tuple with the DcaActivationTimestamp field value
// and a boolean to check if the value has been set.
func (o *Vault) GetDcaActivationTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DcaActivationTimestamp, true
}

// SetDcaActivationTimestamp sets field value
func (o *Vault) SetDcaActivationTimestamp(v string) {
	o.DcaActivationTimestamp = v
}

// GetEnabled returns the Enabled field value
func (o *Vault) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *Vault) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *Vault) SetEnabled(v bool) {
	o.Enabled = v
}

func (o Vault) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pubkey"] = o.Pubkey
	}
	if true {
		toSerialize["protoConfig"] = o.ProtoConfig
	}
	if true {
		toSerialize["tokenAAccount"] = o.TokenAAccount
	}
	if true {
		toSerialize["tokenBAccount"] = o.TokenBAccount
	}
	if true {
		toSerialize["treasuryTokenBAccount"] = o.TreasuryTokenBAccount
	}
	if true {
		toSerialize["tokenAMint"] = o.TokenAMint
	}
	if true {
		toSerialize["tokenBMint"] = o.TokenBMint
	}
	if true {
		toSerialize["lastDcaPeriod"] = o.LastDcaPeriod
	}
	if true {
		toSerialize["dripAmount"] = o.DripAmount
	}
	if true {
		toSerialize["dcaActivationTimestamp"] = o.DcaActivationTimestamp
	}
	if true {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullableVault struct {
	value *Vault
	isSet bool
}

func (v NullableVault) Get() *Vault {
	return v.value
}

func (v *NullableVault) Set(val *Vault) {
	v.value = val
	v.isSet = true
}

func (v NullableVault) IsSet() bool {
	return v.isSet
}

func (v *NullableVault) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVault(val *Vault) *NullableVault {
	return &NullableVault{value: val, isSet: true}
}

func (v NullableVault) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVault) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


