/*
Drip Backend

Drip backend service.

API version: 1.0.0
Contact: dcafmocha@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drip

import (
	"encoding/json"
)

// ListTokenSwapsInner struct for ListTokenSwapsInner
type ListTokenSwapsInner struct {
	Pubkey string `json:"pubkey"`
	Mint string `json:"mint"`
	Authority string `json:"authority"`
	FeeAccount string `json:"feeAccount"`
	TokenAAccount string `json:"tokenAAccount"`
	TokenBAccount string `json:"tokenBAccount"`
	// token pair reference identifier
	Pair string `json:"pair"`
}

// NewListTokenSwapsInner instantiates a new ListTokenSwapsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTokenSwapsInner(pubkey string, mint string, authority string, feeAccount string, tokenAAccount string, tokenBAccount string, pair string) *ListTokenSwapsInner {
	this := ListTokenSwapsInner{}
	this.Pubkey = pubkey
	this.Mint = mint
	this.Authority = authority
	this.FeeAccount = feeAccount
	this.TokenAAccount = tokenAAccount
	this.TokenBAccount = tokenBAccount
	this.Pair = pair
	return &this
}

// NewListTokenSwapsInnerWithDefaults instantiates a new ListTokenSwapsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTokenSwapsInnerWithDefaults() *ListTokenSwapsInner {
	this := ListTokenSwapsInner{}
	return &this
}

// GetPubkey returns the Pubkey field value
func (o *ListTokenSwapsInner) GetPubkey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value
// and a boolean to check if the value has been set.
func (o *ListTokenSwapsInner) GetPubkeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pubkey, true
}

// SetPubkey sets field value
func (o *ListTokenSwapsInner) SetPubkey(v string) {
	o.Pubkey = v
}

// GetMint returns the Mint field value
func (o *ListTokenSwapsInner) GetMint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mint
}

// GetMintOk returns a tuple with the Mint field value
// and a boolean to check if the value has been set.
func (o *ListTokenSwapsInner) GetMintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mint, true
}

// SetMint sets field value
func (o *ListTokenSwapsInner) SetMint(v string) {
	o.Mint = v
}

// GetAuthority returns the Authority field value
func (o *ListTokenSwapsInner) GetAuthority() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Authority
}

// GetAuthorityOk returns a tuple with the Authority field value
// and a boolean to check if the value has been set.
func (o *ListTokenSwapsInner) GetAuthorityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authority, true
}

// SetAuthority sets field value
func (o *ListTokenSwapsInner) SetAuthority(v string) {
	o.Authority = v
}

// GetFeeAccount returns the FeeAccount field value
func (o *ListTokenSwapsInner) GetFeeAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeeAccount
}

// GetFeeAccountOk returns a tuple with the FeeAccount field value
// and a boolean to check if the value has been set.
func (o *ListTokenSwapsInner) GetFeeAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeeAccount, true
}

// SetFeeAccount sets field value
func (o *ListTokenSwapsInner) SetFeeAccount(v string) {
	o.FeeAccount = v
}

// GetTokenAAccount returns the TokenAAccount field value
func (o *ListTokenSwapsInner) GetTokenAAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenAAccount
}

// GetTokenAAccountOk returns a tuple with the TokenAAccount field value
// and a boolean to check if the value has been set.
func (o *ListTokenSwapsInner) GetTokenAAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenAAccount, true
}

// SetTokenAAccount sets field value
func (o *ListTokenSwapsInner) SetTokenAAccount(v string) {
	o.TokenAAccount = v
}

// GetTokenBAccount returns the TokenBAccount field value
func (o *ListTokenSwapsInner) GetTokenBAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenBAccount
}

// GetTokenBAccountOk returns a tuple with the TokenBAccount field value
// and a boolean to check if the value has been set.
func (o *ListTokenSwapsInner) GetTokenBAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenBAccount, true
}

// SetTokenBAccount sets field value
func (o *ListTokenSwapsInner) SetTokenBAccount(v string) {
	o.TokenBAccount = v
}

// GetPair returns the Pair field value
func (o *ListTokenSwapsInner) GetPair() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pair
}

// GetPairOk returns a tuple with the Pair field value
// and a boolean to check if the value has been set.
func (o *ListTokenSwapsInner) GetPairOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pair, true
}

// SetPair sets field value
func (o *ListTokenSwapsInner) SetPair(v string) {
	o.Pair = v
}

func (o ListTokenSwapsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pubkey"] = o.Pubkey
	}
	if true {
		toSerialize["mint"] = o.Mint
	}
	if true {
		toSerialize["authority"] = o.Authority
	}
	if true {
		toSerialize["feeAccount"] = o.FeeAccount
	}
	if true {
		toSerialize["tokenAAccount"] = o.TokenAAccount
	}
	if true {
		toSerialize["tokenBAccount"] = o.TokenBAccount
	}
	if true {
		toSerialize["pair"] = o.Pair
	}
	return json.Marshal(toSerialize)
}

type NullableListTokenSwapsInner struct {
	value *ListTokenSwapsInner
	isSet bool
}

func (v NullableListTokenSwapsInner) Get() *ListTokenSwapsInner {
	return v.value
}

func (v *NullableListTokenSwapsInner) Set(val *ListTokenSwapsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListTokenSwapsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListTokenSwapsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTokenSwapsInner(val *ListTokenSwapsInner) *NullableListTokenSwapsInner {
	return &NullableListTokenSwapsInner{value: val, isSet: true}
}

func (v NullableListTokenSwapsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTokenSwapsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


