/*
Drip Backend

Drip backend service. All API's have a IP rate limit of 10 requests per second. 

API version: 1.0.0
Contact: mocha@dcaf.so
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drip

import (
	"encoding/json"
)

// MintRequest struct for MintRequest
type MintRequest struct {
	Mint string `json:"mint"`
	Wallet string `json:"wallet"`
	Amount string `json:"amount"`
}

// NewMintRequest instantiates a new MintRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMintRequest(mint string, wallet string, amount string) *MintRequest {
	this := MintRequest{}
	this.Mint = mint
	this.Wallet = wallet
	this.Amount = amount
	return &this
}

// NewMintRequestWithDefaults instantiates a new MintRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMintRequestWithDefaults() *MintRequest {
	this := MintRequest{}
	return &this
}

// GetMint returns the Mint field value
func (o *MintRequest) GetMint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mint
}

// GetMintOk returns a tuple with the Mint field value
// and a boolean to check if the value has been set.
func (o *MintRequest) GetMintOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mint, true
}

// SetMint sets field value
func (o *MintRequest) SetMint(v string) {
	o.Mint = v
}

// GetWallet returns the Wallet field value
func (o *MintRequest) GetWallet() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Wallet
}

// GetWalletOk returns a tuple with the Wallet field value
// and a boolean to check if the value has been set.
func (o *MintRequest) GetWalletOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Wallet, true
}

// SetWallet sets field value
func (o *MintRequest) SetWallet(v string) {
	o.Wallet = v
}

// GetAmount returns the Amount field value
func (o *MintRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *MintRequest) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *MintRequest) SetAmount(v string) {
	o.Amount = v
}

func (o MintRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["mint"] = o.Mint
	}
	if true {
		toSerialize["wallet"] = o.Wallet
	}
	if true {
		toSerialize["amount"] = o.Amount
	}
	return json.Marshal(toSerialize)
}

type NullableMintRequest struct {
	value *MintRequest
	isSet bool
}

func (v NullableMintRequest) Get() *MintRequest {
	return v.value
}

func (v *NullableMintRequest) Set(val *MintRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMintRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMintRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMintRequest(val *MintRequest) *NullableMintRequest {
	return &NullableMintRequest{value: val, isSet: true}
}

func (v NullableMintRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMintRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


