/*
Drip Backend

Drip backend service.

API version: 1.0.0
Contact: dcafmocha@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drip

import (
	"encoding/json"
)

// ListTokenPairsInner struct for ListTokenPairsInner
type ListTokenPairsInner struct {
	Id string `json:"id"`
	TokenA string `json:"tokenA"`
	TokenB string `json:"tokenB"`
}

// NewListTokenPairsInner instantiates a new ListTokenPairsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTokenPairsInner(id string, tokenA string, tokenB string) *ListTokenPairsInner {
	this := ListTokenPairsInner{}
	this.Id = id
	this.TokenA = tokenA
	this.TokenB = tokenB
	return &this
}

// NewListTokenPairsInnerWithDefaults instantiates a new ListTokenPairsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTokenPairsInnerWithDefaults() *ListTokenPairsInner {
	this := ListTokenPairsInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListTokenPairsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListTokenPairsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListTokenPairsInner) SetId(v string) {
	o.Id = v
}

// GetTokenA returns the TokenA field value
func (o *ListTokenPairsInner) GetTokenA() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenA
}

// GetTokenAOk returns a tuple with the TokenA field value
// and a boolean to check if the value has been set.
func (o *ListTokenPairsInner) GetTokenAOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenA, true
}

// SetTokenA sets field value
func (o *ListTokenPairsInner) SetTokenA(v string) {
	o.TokenA = v
}

// GetTokenB returns the TokenB field value
func (o *ListTokenPairsInner) GetTokenB() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenB
}

// GetTokenBOk returns a tuple with the TokenB field value
// and a boolean to check if the value has been set.
func (o *ListTokenPairsInner) GetTokenBOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenB, true
}

// SetTokenB sets field value
func (o *ListTokenPairsInner) SetTokenB(v string) {
	o.TokenB = v
}

func (o ListTokenPairsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["tokenA"] = o.TokenA
	}
	if true {
		toSerialize["tokenB"] = o.TokenB
	}
	return json.Marshal(toSerialize)
}

type NullableListTokenPairsInner struct {
	value *ListTokenPairsInner
	isSet bool
}

func (v NullableListTokenPairsInner) Get() *ListTokenPairsInner {
	return v.value
}

func (v *NullableListTokenPairsInner) Set(val *ListTokenPairsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListTokenPairsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListTokenPairsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTokenPairsInner(val *ListTokenPairsInner) *NullableListTokenPairsInner {
	return &NullableListTokenPairsInner{value: val, isSet: true}
}

func (v NullableListTokenPairsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTokenPairsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


