/*
Drip Backend

Drip backend service.

API version: 1.0.0
Contact: dcafmocha@protonmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drip

import (
	"encoding/json"
)

// ListPositionsInner struct for ListPositionsInner
type ListPositionsInner struct {
	Pubkey string `json:"pubkey"`
	Vault string `json:"vault"`
	Authority string `json:"authority"`
	DepositedTokenAAmount int32 `json:"depositedTokenAAmount"`
	WithdrawnTokenBAmount int32 `json:"withdrawnTokenBAmount"`
	DepositTimestamp string `json:"depositTimestamp"`
	DcaPeriodIdBeforeDeposit int32 `json:"dcaPeriodIdBeforeDeposit"`
	NumberOfSwaps int32 `json:"numberOfSwaps"`
	PeriodicDripAmount int32 `json:"periodicDripAmount"`
	IsClosed bool `json:"isClosed"`
}

// NewListPositionsInner instantiates a new ListPositionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPositionsInner(pubkey string, vault string, authority string, depositedTokenAAmount int32, withdrawnTokenBAmount int32, depositTimestamp string, dcaPeriodIdBeforeDeposit int32, numberOfSwaps int32, periodicDripAmount int32, isClosed bool) *ListPositionsInner {
	this := ListPositionsInner{}
	this.Pubkey = pubkey
	this.Vault = vault
	this.Authority = authority
	this.DepositedTokenAAmount = depositedTokenAAmount
	this.WithdrawnTokenBAmount = withdrawnTokenBAmount
	this.DepositTimestamp = depositTimestamp
	this.DcaPeriodIdBeforeDeposit = dcaPeriodIdBeforeDeposit
	this.NumberOfSwaps = numberOfSwaps
	this.PeriodicDripAmount = periodicDripAmount
	this.IsClosed = isClosed
	return &this
}

// NewListPositionsInnerWithDefaults instantiates a new ListPositionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPositionsInnerWithDefaults() *ListPositionsInner {
	this := ListPositionsInner{}
	return &this
}

// GetPubkey returns the Pubkey field value
func (o *ListPositionsInner) GetPubkey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value
// and a boolean to check if the value has been set.
func (o *ListPositionsInner) GetPubkeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pubkey, true
}

// SetPubkey sets field value
func (o *ListPositionsInner) SetPubkey(v string) {
	o.Pubkey = v
}

// GetVault returns the Vault field value
func (o *ListPositionsInner) GetVault() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vault
}

// GetVaultOk returns a tuple with the Vault field value
// and a boolean to check if the value has been set.
func (o *ListPositionsInner) GetVaultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vault, true
}

// SetVault sets field value
func (o *ListPositionsInner) SetVault(v string) {
	o.Vault = v
}

// GetAuthority returns the Authority field value
func (o *ListPositionsInner) GetAuthority() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Authority
}

// GetAuthorityOk returns a tuple with the Authority field value
// and a boolean to check if the value has been set.
func (o *ListPositionsInner) GetAuthorityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Authority, true
}

// SetAuthority sets field value
func (o *ListPositionsInner) SetAuthority(v string) {
	o.Authority = v
}

// GetDepositedTokenAAmount returns the DepositedTokenAAmount field value
func (o *ListPositionsInner) GetDepositedTokenAAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DepositedTokenAAmount
}

// GetDepositedTokenAAmountOk returns a tuple with the DepositedTokenAAmount field value
// and a boolean to check if the value has been set.
func (o *ListPositionsInner) GetDepositedTokenAAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DepositedTokenAAmount, true
}

// SetDepositedTokenAAmount sets field value
func (o *ListPositionsInner) SetDepositedTokenAAmount(v int32) {
	o.DepositedTokenAAmount = v
}

// GetWithdrawnTokenBAmount returns the WithdrawnTokenBAmount field value
func (o *ListPositionsInner) GetWithdrawnTokenBAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WithdrawnTokenBAmount
}

// GetWithdrawnTokenBAmountOk returns a tuple with the WithdrawnTokenBAmount field value
// and a boolean to check if the value has been set.
func (o *ListPositionsInner) GetWithdrawnTokenBAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WithdrawnTokenBAmount, true
}

// SetWithdrawnTokenBAmount sets field value
func (o *ListPositionsInner) SetWithdrawnTokenBAmount(v int32) {
	o.WithdrawnTokenBAmount = v
}

// GetDepositTimestamp returns the DepositTimestamp field value
func (o *ListPositionsInner) GetDepositTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DepositTimestamp
}

// GetDepositTimestampOk returns a tuple with the DepositTimestamp field value
// and a boolean to check if the value has been set.
func (o *ListPositionsInner) GetDepositTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DepositTimestamp, true
}

// SetDepositTimestamp sets field value
func (o *ListPositionsInner) SetDepositTimestamp(v string) {
	o.DepositTimestamp = v
}

// GetDcaPeriodIdBeforeDeposit returns the DcaPeriodIdBeforeDeposit field value
func (o *ListPositionsInner) GetDcaPeriodIdBeforeDeposit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DcaPeriodIdBeforeDeposit
}

// GetDcaPeriodIdBeforeDepositOk returns a tuple with the DcaPeriodIdBeforeDeposit field value
// and a boolean to check if the value has been set.
func (o *ListPositionsInner) GetDcaPeriodIdBeforeDepositOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DcaPeriodIdBeforeDeposit, true
}

// SetDcaPeriodIdBeforeDeposit sets field value
func (o *ListPositionsInner) SetDcaPeriodIdBeforeDeposit(v int32) {
	o.DcaPeriodIdBeforeDeposit = v
}

// GetNumberOfSwaps returns the NumberOfSwaps field value
func (o *ListPositionsInner) GetNumberOfSwaps() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NumberOfSwaps
}

// GetNumberOfSwapsOk returns a tuple with the NumberOfSwaps field value
// and a boolean to check if the value has been set.
func (o *ListPositionsInner) GetNumberOfSwapsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumberOfSwaps, true
}

// SetNumberOfSwaps sets field value
func (o *ListPositionsInner) SetNumberOfSwaps(v int32) {
	o.NumberOfSwaps = v
}

// GetPeriodicDripAmount returns the PeriodicDripAmount field value
func (o *ListPositionsInner) GetPeriodicDripAmount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PeriodicDripAmount
}

// GetPeriodicDripAmountOk returns a tuple with the PeriodicDripAmount field value
// and a boolean to check if the value has been set.
func (o *ListPositionsInner) GetPeriodicDripAmountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PeriodicDripAmount, true
}

// SetPeriodicDripAmount sets field value
func (o *ListPositionsInner) SetPeriodicDripAmount(v int32) {
	o.PeriodicDripAmount = v
}

// GetIsClosed returns the IsClosed field value
func (o *ListPositionsInner) GetIsClosed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsClosed
}

// GetIsClosedOk returns a tuple with the IsClosed field value
// and a boolean to check if the value has been set.
func (o *ListPositionsInner) GetIsClosedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsClosed, true
}

// SetIsClosed sets field value
func (o *ListPositionsInner) SetIsClosed(v bool) {
	o.IsClosed = v
}

func (o ListPositionsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pubkey"] = o.Pubkey
	}
	if true {
		toSerialize["vault"] = o.Vault
	}
	if true {
		toSerialize["authority"] = o.Authority
	}
	if true {
		toSerialize["depositedTokenAAmount"] = o.DepositedTokenAAmount
	}
	if true {
		toSerialize["withdrawnTokenBAmount"] = o.WithdrawnTokenBAmount
	}
	if true {
		toSerialize["depositTimestamp"] = o.DepositTimestamp
	}
	if true {
		toSerialize["dcaPeriodIdBeforeDeposit"] = o.DcaPeriodIdBeforeDeposit
	}
	if true {
		toSerialize["numberOfSwaps"] = o.NumberOfSwaps
	}
	if true {
		toSerialize["periodicDripAmount"] = o.PeriodicDripAmount
	}
	if true {
		toSerialize["isClosed"] = o.IsClosed
	}
	return json.Marshal(toSerialize)
}

type NullableListPositionsInner struct {
	value *ListPositionsInner
	isSet bool
}

func (v NullableListPositionsInner) Get() *ListPositionsInner {
	return v.value
}

func (v *NullableListPositionsInner) Set(val *ListPositionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListPositionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListPositionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPositionsInner(val *ListPositionsInner) *NullableListPositionsInner {
	return &NullableListPositionsInner{value: val, isSet: true}
}

func (v NullableListPositionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPositionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


