environment: DEV
triggerDCA:
  - vault: "123"
    vaultProtoConfig: "123"
    vaultTokenAAccount: "123"
    vaultTokenBAccount: "123"
    tokenAMint: "123"
    tokenBMint: "123"
    swapTokenMint: "123"
    swapTokenAAccount: "123"
    swapTokenBAccount: "123"
    swapFeeAccount: "123"
    swapAuthority: "123"
    swap: "123"
  - vault: "456"
    vaultProtoConfig: "456"
    vaultTokenAAccount: "456"
    vaultTokenBAccount: "456"
    tokenAMint: "456"
    tokenBMint: "456"
    swapTokenMint: "456"
    swapTokenAAccount: "456"
    swapTokenBAccount: "456"
    swapFeeAccount: "456"
    swapAuthority: "456"
    swap: "456"
