environment: DEVNET
triggerDCA:
  - vault: EJo9MwRvo94MsnnNQuCwuJW5LkzEmG5XgQCs8hp8x9Xa
    vaultProtoConfig: HXbcs2S2exrC36RqcDZXNCCbNKPDBJq5pHmmyE9tvzMw
    vaultProtoConfigGranularity: 60
    vaultTokenAAccount: AraHKTsGgcaTMBrFNFxjhgScJxaooC1Q3qSAAfnpZS6U
    vaultTokenBAccount: ApEYLfsD9kXvSkykfkfcUfhV326vd4eG3ntXKBMX466h
    vaultTreasuryTokenBAccount: 7NaW4PXzRarnpd9EboHtBRSCTvbRHd3bykzSzMWEdt8U
    tokenAMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenASymbol: SOL
    tokenBMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenBSymbol: USDC
    swapTokenMint: 37qDKaBiVnNwJP2p8nTH6igtENWVoWCzETK2UsNotYTc
    swapTokenAAccount: GeQpUK8WcGZfb6GLNoAtyibp2qJcwkGuNF1dXjUtpsRG
    swapTokenBAccount: zn2CDAJgRfQiLNXgg6RYUzoxmjWpsMGjuz1RC3sEX1D
    swapFeeAccount: 8Zk91xbVEQDPMS3wg959KpRSNEuW3Fd7CCFAv4nPNdDQ
    swapAuthority: ABXUGaqzcKtSxZaKhtaiHZoNVLyfryhNzjTnNw2Ky2sc
    swap: G7Urrkwvz5GwMwXLupdiBRfjhU9VcrnbdNEQ7baWGHuj
  - vault: Hr2FmtjkKMLd6EyrFU3FaWrg5kYHZ5PaZm3YJGoGhHF1
    vaultProtoConfig: 9u6V96if8ybNNE71d72fMuj3yv2BPZujnqyPqZhN2yeP
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: 6o32YsZi9fLjVnr9o1rpvVqW3rKnKrG7rERkZGZY9zbY
    vaultTokenBAccount: FgjEKkwBYeDmDVm5e7oFfM1ojj1NGr8LHk1L7amh37kt
    vaultTreasuryTokenBAccount: 7NaW4PXzRarnpd9EboHtBRSCTvbRHd3bykzSzMWEdt8U
    tokenAMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenASymbol: SOL
    tokenBMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenBSymbol: USDC
    swapTokenMint: 37qDKaBiVnNwJP2p8nTH6igtENWVoWCzETK2UsNotYTc
    swapTokenAAccount: GeQpUK8WcGZfb6GLNoAtyibp2qJcwkGuNF1dXjUtpsRG
    swapTokenBAccount: zn2CDAJgRfQiLNXgg6RYUzoxmjWpsMGjuz1RC3sEX1D
    swapFeeAccount: 8Zk91xbVEQDPMS3wg959KpRSNEuW3Fd7CCFAv4nPNdDQ
    swapAuthority: ABXUGaqzcKtSxZaKhtaiHZoNVLyfryhNzjTnNw2Ky2sc
    swap: G7Urrkwvz5GwMwXLupdiBRfjhU9VcrnbdNEQ7baWGHuj
  - vault: HDwiMMmrwpoernDTVxDrxMRTLPY8ykv9XvqGJGfkGFeY
    vaultProtoConfig: GXVwjYfLE7ptjGfztLfwYuchLaspXs4UBohM9dSH3Yp7
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: C3vKz99WgY88yuqYjMLpegotwVHNgVe1F3yw8veiMPub
    vaultTokenBAccount: ECGRNVZ37oiN8fGYcC5hmSckUb1SRWRJxgZRZSP3JGvb
    vaultTreasuryTokenBAccount: 7NaW4PXzRarnpd9EboHtBRSCTvbRHd3bykzSzMWEdt8U
    tokenAMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenASymbol: SOL
    tokenBMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenBSymbol: USDC
    swapTokenMint: 37qDKaBiVnNwJP2p8nTH6igtENWVoWCzETK2UsNotYTc
    swapTokenAAccount: GeQpUK8WcGZfb6GLNoAtyibp2qJcwkGuNF1dXjUtpsRG
    swapTokenBAccount: zn2CDAJgRfQiLNXgg6RYUzoxmjWpsMGjuz1RC3sEX1D
    swapFeeAccount: 8Zk91xbVEQDPMS3wg959KpRSNEuW3Fd7CCFAv4nPNdDQ
    swapAuthority: ABXUGaqzcKtSxZaKhtaiHZoNVLyfryhNzjTnNw2Ky2sc
    swap: G7Urrkwvz5GwMwXLupdiBRfjhU9VcrnbdNEQ7baWGHuj
  - vault: 6aPBden1FrTQZS4eKhBodD1cprhUKfXFBDx72Q3wpAd8
    vaultProtoConfig: oazp9SJYuGAfyEaDT5zrMq6nyYcgBEEUzL26tVVC4HY
    vaultProtoConfigGranularity: 60
    vaultTokenAAccount: AzrFWb1QgHTvUcvRMECKVtZoxs1qzjf6UiGZGP592ydq
    vaultTokenBAccount: 52pDZHHnq5RMR8F6fi8diFxGv2H1j2ZKKWWsSWws1kPf
    vaultTreasuryTokenBAccount: 7NaW4PXzRarnpd9EboHtBRSCTvbRHd3bykzSzMWEdt8U
    tokenAMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenASymbol: ORCA
    tokenBMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenBSymbol: USDC
    swapTokenMint: 58CXp3cALgrcgZrMe8jgXH2Ku9nM2aKjTP5AePcCt6Ka
    swapTokenAAccount: 6FDd1R6A2LLoZeEdnm97w78gvfjoCHhC8nmSxeCDrxtH
    swapTokenBAccount: 4djxhueUfnsDpNFtYUudgtxGGsYy43TwwpjoUVVJfJHZ
    swapFeeAccount: 5yraimvTLmMsdrp5fD2oa8bP3KWr8c5AbNig7bHoz8Bo
    swapAuthority: 9BRTPhDnQH7ZEG1ezuyTjXbwEB6JTyGxZdVnQkXiRXXZ
    swap: A3pCAwmdi6tvq4S79i8iQD2ZZgpFDQ7wcW493jWsjuHy
  - vault: 51thEEg7EEv9SEW5P9SBgHqT8tsfNbUecvfkW16gsan9
    vaultProtoConfig: C9dUWjX7YpoGhgHKFjF1mKcLhzCop5Q1tuufhf9tGwcu
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: JAA8ZsJiJmiKuHmS8gVXLZXshfaHQqGWztCwXa1vSAJn
    vaultTokenBAccount: B4SUZ6Pf4KsJhY9obBAqY5Ume2mwKDeUTwfYXdmLseGY
    vaultTreasuryTokenBAccount: 7NaW4PXzRarnpd9EboHtBRSCTvbRHd3bykzSzMWEdt8U
    tokenAMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenASymbol: ORCA
    tokenBMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenBSymbol: USDC
    swapTokenMint: 58CXp3cALgrcgZrMe8jgXH2Ku9nM2aKjTP5AePcCt6Ka
    swapTokenAAccount: 6FDd1R6A2LLoZeEdnm97w78gvfjoCHhC8nmSxeCDrxtH
    swapTokenBAccount: 4djxhueUfnsDpNFtYUudgtxGGsYy43TwwpjoUVVJfJHZ
    swapFeeAccount: 5yraimvTLmMsdrp5fD2oa8bP3KWr8c5AbNig7bHoz8Bo
    swapAuthority: 9BRTPhDnQH7ZEG1ezuyTjXbwEB6JTyGxZdVnQkXiRXXZ
    swap: A3pCAwmdi6tvq4S79i8iQD2ZZgpFDQ7wcW493jWsjuHy
  - vault: 2zBhrUKqX7UP9UhKiaC16MCU7bJ9FvjZhDtDc6yB1utD
    vaultProtoConfig: FGyGMk9PVWtvWAkAB6UGNbcXxb7UnhEyU72Fbv2qTqUM
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: 2aLyN4acMq4nxxkjrxnMA2GomF6ByFHXFQu1MXPM9QR2
    vaultTokenBAccount: BpsWQyw4F1JdxC9VEDe6b8onU42a1hTfeWcyVMDgrkCA
    vaultTreasuryTokenBAccount: 7NaW4PXzRarnpd9EboHtBRSCTvbRHd3bykzSzMWEdt8U
    tokenAMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenASymbol: ORCA
    tokenBMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenBSymbol: USDC
    swapTokenMint: 58CXp3cALgrcgZrMe8jgXH2Ku9nM2aKjTP5AePcCt6Ka
    swapTokenAAccount: 6FDd1R6A2LLoZeEdnm97w78gvfjoCHhC8nmSxeCDrxtH
    swapTokenBAccount: 4djxhueUfnsDpNFtYUudgtxGGsYy43TwwpjoUVVJfJHZ
    swapFeeAccount: 5yraimvTLmMsdrp5fD2oa8bP3KWr8c5AbNig7bHoz8Bo
    swapAuthority: 9BRTPhDnQH7ZEG1ezuyTjXbwEB6JTyGxZdVnQkXiRXXZ
    swap: A3pCAwmdi6tvq4S79i8iQD2ZZgpFDQ7wcW493jWsjuHy
  - vault: 3S62Y4Zutkr73Krh4UwBJewYhHr6q2wWjZGFLBM8mWUC
    vaultProtoConfig: 4A87ZpDramFGHwPABoVpRWtUaJvsm3LgefPqwWDpUhdV
    vaultProtoConfigGranularity: 60
    vaultTokenAAccount: 8azwaeuAV3pBBq6VBXToZa2tQzpQg5Rmt6MrRMQmwnFx
    vaultTokenBAccount: 8cPXJRyjMg1iSRuV1m9tq2UGWeQHDZCdj9KTdNEDg49G
    vaultTreasuryTokenBAccount: 6MMH43yxADFr8es61jmbkW7Q3KXsKVHYpEfhGmpPz4h6
    tokenAMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenASymbol: USDC
    tokenBMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenBSymbol: SOL
    swapTokenMint: 3Bp6anXxFi4Q6MFTG1u4ueTpT3rSAzQswnHpamKHu5a8
    swapTokenAAccount: 7xm6RW9ZzdY5749DtRiWH4FaP8HKueJU3CobetyeDFLR
    swapTokenBAccount: 2YQ7Fs2SVJaBok8PXaugue4MekrUVGqKVNQ8UE4FwLZX
    swapFeeAccount: ERbzyXYH6DkKRZAg5d776NXC949Mc6SUkaNxr4P7Yys3
    swapAuthority: CEaTWDaH4PNwz5PNXEJyvRU4XfpoGmyeMthXEFWBNx5t
    swap: FzF4hSHPoZLuA3FTdifkb8WayjqoV7321hSAWQzfUnM4
  - vault: BdkJ8WWtpSFsFcaLgmCAwa7SVADMuCikZe4mAhgRuHAo
    vaultProtoConfig: B7kUk469u5mMMcCrVQW8TWCZDVikVE8k8Z68R3hYWGsY
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: 9AvqAxYRc9ZzmB5TQmbuTWe74zEyoX3cDF9pBGMp6P4x
    vaultTokenBAccount: CHwmWYzTB1w2p4iYJR1wq4yWDrj8StvJTAN5NQcH1iiy
    vaultTreasuryTokenBAccount: 6MMH43yxADFr8es61jmbkW7Q3KXsKVHYpEfhGmpPz4h6
    tokenAMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenASymbol: USDC
    tokenBMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenBSymbol: SOL
    swapTokenMint: 3Bp6anXxFi4Q6MFTG1u4ueTpT3rSAzQswnHpamKHu5a8
    swapTokenAAccount: 7xm6RW9ZzdY5749DtRiWH4FaP8HKueJU3CobetyeDFLR
    swapTokenBAccount: 2YQ7Fs2SVJaBok8PXaugue4MekrUVGqKVNQ8UE4FwLZX
    swapFeeAccount: ERbzyXYH6DkKRZAg5d776NXC949Mc6SUkaNxr4P7Yys3
    swapAuthority: CEaTWDaH4PNwz5PNXEJyvRU4XfpoGmyeMthXEFWBNx5t
    swap: FzF4hSHPoZLuA3FTdifkb8WayjqoV7321hSAWQzfUnM4
  - vault: 8pYFvRASdrTkybYEfsq7E2fTL8Df9P3QK1wwQJoSxtYG
    vaultProtoConfig: Bsf1SFvtR82VuQiyJ7S7HcZDbLc5R1UWdFQVFJXJrX9E
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: FNFANZCcn9QPKaK4WJTKM4c78pHq3Z4G88DoQxFA6pFk
    vaultTokenBAccount: 6SHLiX1Rx5GyTw9hu7rjL5g1pe9PC9m9kPexgDANm1Ci
    vaultTreasuryTokenBAccount: 6MMH43yxADFr8es61jmbkW7Q3KXsKVHYpEfhGmpPz4h6
    tokenAMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenASymbol: USDC
    tokenBMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenBSymbol: SOL
    swapTokenMint: 3Bp6anXxFi4Q6MFTG1u4ueTpT3rSAzQswnHpamKHu5a8
    swapTokenAAccount: 7xm6RW9ZzdY5749DtRiWH4FaP8HKueJU3CobetyeDFLR
    swapTokenBAccount: 2YQ7Fs2SVJaBok8PXaugue4MekrUVGqKVNQ8UE4FwLZX
    swapFeeAccount: ERbzyXYH6DkKRZAg5d776NXC949Mc6SUkaNxr4P7Yys3
    swapAuthority: CEaTWDaH4PNwz5PNXEJyvRU4XfpoGmyeMthXEFWBNx5t
    swap: FzF4hSHPoZLuA3FTdifkb8WayjqoV7321hSAWQzfUnM4
  - vault: CANTb7KHUKuZ1HQR73Exo8W14jSLLndcRx2KizxSBEbB
    vaultProtoConfig: 6UjFL22VY4MwDkgAjrHF3iu9unyRJAYD3qUqNZNoC9b2
    vaultProtoConfigGranularity: 60
    vaultTokenAAccount: F6tv4ZaGuq4YaJ8Jit7ctRTWj8zQRPbJuhjR3QE87HC1
    vaultTokenBAccount: GU3CGjita9LwuWAbXn5RfoLr3oTaHw9EQnyaRzb5a1ef
    vaultTreasuryTokenBAccount: 6MMH43yxADFr8es61jmbkW7Q3KXsKVHYpEfhGmpPz4h6
    tokenAMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenASymbol: ORCA
    tokenBMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenBSymbol: SOL
    swapTokenMint: 4cw3JXYvWCPtpgxhp6PHqsVsvpqXg8kUxgkoMDEpMJPR
    swapTokenAAccount: 26kmfecVP8yZBKGEXhQtPN2VvUvVxMHutwkAt2uGdshG
    swapTokenBAccount: 9wJA5uCuENaCHzkegqBSpMzvLUvhQUw3od8uAUzC2Mvq
    swapFeeAccount: EAPxrLuTuWikH3ZsG6FufaKbKQfPy5LC16Y2Vqhe93XX
    swapAuthority: A1Qfi5Z4HoHC8dQqL9rr3Eyj3J6BwP3poYSkchqPVoUd
    swap: G2BWsskv1DQv2qyUD6KoGjRpavCzLipjooy2h9X4nN2U
  - vault: GYR41hrsrrmPCCkpLDwQ4R4n8e9YHKaJg1LBeTi2X3Qs
    vaultProtoConfig: 3bSW7HC5kTpmGavcq3dCPEGBA7u1i5Fc375G9pjoVwkt
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: BMePLoneMhiAWvq7vvSLqfxuaHmG4GbNsUjkJooDKpT6
    vaultTokenBAccount: 3WnpcLcR7oNehvQuLJ6q3qRRXtag4qXK3CBErFqZvz42
    vaultTreasuryTokenBAccount: 6MMH43yxADFr8es61jmbkW7Q3KXsKVHYpEfhGmpPz4h6
    tokenAMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenASymbol: ORCA
    tokenBMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenBSymbol: SOL
    swapTokenMint: 4cw3JXYvWCPtpgxhp6PHqsVsvpqXg8kUxgkoMDEpMJPR
    swapTokenAAccount: 26kmfecVP8yZBKGEXhQtPN2VvUvVxMHutwkAt2uGdshG
    swapTokenBAccount: 9wJA5uCuENaCHzkegqBSpMzvLUvhQUw3od8uAUzC2Mvq
    swapFeeAccount: EAPxrLuTuWikH3ZsG6FufaKbKQfPy5LC16Y2Vqhe93XX
    swapAuthority: A1Qfi5Z4HoHC8dQqL9rr3Eyj3J6BwP3poYSkchqPVoUd
    swap: G2BWsskv1DQv2qyUD6KoGjRpavCzLipjooy2h9X4nN2U
  - vault: CM5TUBE74KSUMWAhwkPLNgNzRBvAHNksZHSaCbLjn7sb
    vaultProtoConfig: DcuA4pbNtiUrNkwVMoKCCSD77NgSE2uiq2nGdFyuCbdf
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: 2oUJGX7a8mbhRHQQu8S7M4YMV4LRckTb9RD5waM5Rtbz
    vaultTokenBAccount: 8V6AAm7hmNxd2FRHDXPfjFnH4CntLMCSu4SPcpBrt76H
    vaultTreasuryTokenBAccount: 6MMH43yxADFr8es61jmbkW7Q3KXsKVHYpEfhGmpPz4h6
    tokenAMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenASymbol: ORCA
    tokenBMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenBSymbol: SOL
    swapTokenMint: 4cw3JXYvWCPtpgxhp6PHqsVsvpqXg8kUxgkoMDEpMJPR
    swapTokenAAccount: 26kmfecVP8yZBKGEXhQtPN2VvUvVxMHutwkAt2uGdshG
    swapTokenBAccount: 9wJA5uCuENaCHzkegqBSpMzvLUvhQUw3od8uAUzC2Mvq
    swapFeeAccount: EAPxrLuTuWikH3ZsG6FufaKbKQfPy5LC16Y2Vqhe93XX
    swapAuthority: A1Qfi5Z4HoHC8dQqL9rr3Eyj3J6BwP3poYSkchqPVoUd
    swap: G2BWsskv1DQv2qyUD6KoGjRpavCzLipjooy2h9X4nN2U
  - vault: 4xZxj3VCp2e1ST3gnUdhYvSAnCenCoMBzRPtGXUyZwBf
    vaultProtoConfig: J2ipdPYZSt6yCQoykFFmtce2dkX1GM4xpDXaKrTZwM2h
    vaultProtoConfigGranularity: 60
    vaultTokenAAccount: 52kk8ddu3ukQx5GDnCCbA5xvuNrmdDRhqr87hpLCQMo5
    vaultTokenBAccount: D1k3iPGJMKnEGrhFTvMV84FcetyDYZDWkhpuVd2pWyZm
    vaultTreasuryTokenBAccount: AUMGiTLNLa9mbkTnGetU5tXKxAV8q1rwDSg59iurzNHh
    tokenAMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenASymbol: USDC
    tokenBMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenBSymbol: ORCA
    swapTokenMint: 4gVKQpJsdANp1o4Kgj1Tcn7dMGxzTnK8tcXcy7r2MJZ2
    swapTokenAAccount: FoRQ515htZxNAMaB9m8s3njqPcyC5B6P718wsTGghzup
    swapTokenBAccount: 4U9RWtjMFk3ReJSHxDnDccZp4N6jUmzeL8m1Xr6mGaY2
    swapFeeAccount: 9GapgtADa1nEoZG1c7Cxm9rTmpTcEdoDcbHnNuaZGvAZ
    swapAuthority: BK4FE82VPh5HAk3mN67pSwPpsvcLPtDj2eRuuP3nLXzX
    swap: YdqK6zog9isZTFks5FVzaeRR2s3sHCvXqrpn6NixT8E
  - vault: 4hZ6xLkYdS5iuaJ2NyqxHqwGgsAqieP473Q63xojeLhr
    vaultProtoConfig: EeTfAtZqBgknzLForzbbpdzWNnBPh2bXGtjXjkDeRWig
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: 7SG9EMcXQZENMdZvp3qyvhuAff9TtUPKs6DYRfsCoSQn
    vaultTokenBAccount: BAkadguRtuB1o1pt8gMNDDRSoPdohZ8SfQH73vc9NswP
    vaultTreasuryTokenBAccount: AUMGiTLNLa9mbkTnGetU5tXKxAV8q1rwDSg59iurzNHh
    tokenAMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenASymbol: USDC
    tokenBMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenBSymbol: ORCA
    swapTokenMint: 4gVKQpJsdANp1o4Kgj1Tcn7dMGxzTnK8tcXcy7r2MJZ2
    swapTokenAAccount: FoRQ515htZxNAMaB9m8s3njqPcyC5B6P718wsTGghzup
    swapTokenBAccount: 4U9RWtjMFk3ReJSHxDnDccZp4N6jUmzeL8m1Xr6mGaY2
    swapFeeAccount: 9GapgtADa1nEoZG1c7Cxm9rTmpTcEdoDcbHnNuaZGvAZ
    swapAuthority: BK4FE82VPh5HAk3mN67pSwPpsvcLPtDj2eRuuP3nLXzX
    swap: YdqK6zog9isZTFks5FVzaeRR2s3sHCvXqrpn6NixT8E
  - vault: 8hynQ6FRYbPmh55DEWeG9N8m8VhJFJ1BhtER3RMWgrgA
    vaultProtoConfig: 3y4tB4zb9s4o46DHYvCSAg4DoA9WmrTYiP9rmptzazYS
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: 8xktZwjUY7uqKYbcU6oFFhDHCpoM26Z3eQC3ZwfDS4an
    vaultTokenBAccount: 2PLsLskRCDfPL6nAaPqzsfwNeAkHmaxZ2SsgK8qyxye3
    vaultTreasuryTokenBAccount: AUMGiTLNLa9mbkTnGetU5tXKxAV8q1rwDSg59iurzNHh
    tokenAMint: 31nFDfb3b4qw8JPx4FaXGgEk8omt7NuHpPkwWCSym5rC
    tokenASymbol: USDC
    tokenBMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenBSymbol: ORCA
    swapTokenMint: 4gVKQpJsdANp1o4Kgj1Tcn7dMGxzTnK8tcXcy7r2MJZ2
    swapTokenAAccount: FoRQ515htZxNAMaB9m8s3njqPcyC5B6P718wsTGghzup
    swapTokenBAccount: 4U9RWtjMFk3ReJSHxDnDccZp4N6jUmzeL8m1Xr6mGaY2
    swapFeeAccount: 9GapgtADa1nEoZG1c7Cxm9rTmpTcEdoDcbHnNuaZGvAZ
    swapAuthority: BK4FE82VPh5HAk3mN67pSwPpsvcLPtDj2eRuuP3nLXzX
    swap: YdqK6zog9isZTFks5FVzaeRR2s3sHCvXqrpn6NixT8E
  - vault: 5nh2m5s9Lc6CFM4mUfhYDSzfKaTGHtw7CEEW6Vt5Asd8
    vaultProtoConfig: HSRfhZ1LNhsV5qGw6PakskMv519UC61BU1FBotZ6hp6S
    vaultProtoConfigGranularity: 60
    vaultTokenAAccount: BumYDnhnUGi3nC2VfmzRhoSvdrAPyoP6DBAgddRABakM
    vaultTokenBAccount: CQEKPq38m9WCs4hgK4hE9rFkDzATE38a4ojTtv79p61D
    vaultTreasuryTokenBAccount: AUMGiTLNLa9mbkTnGetU5tXKxAV8q1rwDSg59iurzNHh
    tokenAMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenASymbol: SOL
    tokenBMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenBSymbol: ORCA
    swapTokenMint: BZ9rexfhhFq8xGQv9b8dqT9YQ6TRmM1GL1x774iSYTAY
    swapTokenAAccount: HDTDkShhKdWWTQpH26Xc2ytEG8zWcQBL8yLAAihai7FE
    swapTokenBAccount: 4XSDnsMbsHMiukrePDhv3k6UzG3PX4avq7r5bzm9jgCB
    swapFeeAccount: 9VbVcps4A6nRQJBq7ZoofYdnKKQ62b6Pu7kAffsYuGiW
    swapAuthority: 87C4X2FXZTySCxSFPPukyQYWmDxbrp4SUbHa4VZCPvCQ
    swap: 7tA1hR52oAEYv7ZieeWKHXbd3GXJDKAgFqgodcWzyGnj
  - vault: C8ecew6Tar7KsQyLyxEXfeJsNSPcMqp3zsHARV9LUsUm
    vaultProtoConfig: 9NA1M7nUVjx8YjLTNBBSh8Nip8u7eUiky4874TqCKtPV
    vaultProtoConfigGranularity: 3600
    vaultTokenAAccount: A6YGkx1Vrw7g6PR8Px7JtJDV9gXou7Mawq9kPR8BAJLZ
    vaultTokenBAccount: B3RMu1AfvB7tbgguLw6cERjJuPaL84wNJ7QDJku8xmrU
    vaultTreasuryTokenBAccount: AUMGiTLNLa9mbkTnGetU5tXKxAV8q1rwDSg59iurzNHh
    tokenAMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenASymbol: SOL
    tokenBMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenBSymbol: ORCA
    swapTokenMint: BZ9rexfhhFq8xGQv9b8dqT9YQ6TRmM1GL1x774iSYTAY
    swapTokenAAccount: HDTDkShhKdWWTQpH26Xc2ytEG8zWcQBL8yLAAihai7FE
    swapTokenBAccount: 4XSDnsMbsHMiukrePDhv3k6UzG3PX4avq7r5bzm9jgCB
    swapFeeAccount: 9VbVcps4A6nRQJBq7ZoofYdnKKQ62b6Pu7kAffsYuGiW
    swapAuthority: 87C4X2FXZTySCxSFPPukyQYWmDxbrp4SUbHa4VZCPvCQ
    swap: 7tA1hR52oAEYv7ZieeWKHXbd3GXJDKAgFqgodcWzyGnj
  - vault: F6QdjkbCccrTj9CmQvXhcRXHst4chjMGpgp24sG72uiP
    vaultProtoConfig: 85qfS368GnaBTWPdFkmqeM5v8mrvY8ZgbFL8YRc5Mcf5
    vaultProtoConfigGranularity: 86400
    vaultTokenAAccount: 3Xxb8f3FErqAmK2bWaLE5bt2jvG3bW9XRLX7kDTTpJDe
    vaultTokenBAccount: CyyyQUoxadp7F5sMrSWUoMfz4AC4emx82ZXFaNDLcVm5
    vaultTreasuryTokenBAccount: AUMGiTLNLa9mbkTnGetU5tXKxAV8q1rwDSg59iurzNHh
    tokenAMint: EpurvB9cZ9WkcFePxH7V8vNpZy3nGQLsp2gcGehAWcAL
    tokenASymbol: SOL
    tokenBMint: 9gAMFwMubEvQi6Tts5ePezJp6BqD72FVWECVgaNh9BpG
    tokenBSymbol: ORCA
    swapTokenMint: BZ9rexfhhFq8xGQv9b8dqT9YQ6TRmM1GL1x774iSYTAY
    swapTokenAAccount: HDTDkShhKdWWTQpH26Xc2ytEG8zWcQBL8yLAAihai7FE
    swapTokenBAccount: 4XSDnsMbsHMiukrePDhv3k6UzG3PX4avq7r5bzm9jgCB
    swapFeeAccount: 9VbVcps4A6nRQJBq7ZoofYdnKKQ62b6Pu7kAffsYuGiW
    swapAuthority: 87C4X2FXZTySCxSFPPukyQYWmDxbrp4SUbHa4VZCPvCQ
    swap: 7tA1hR52oAEYv7ZieeWKHXbd3GXJDKAgFqgodcWzyGnj
