environment: LOCALNET
triggerDCA:
  - vault: CTbFDNMiCzR9BKLR3XUuVyWzaP2miZBZvEucdR1fxbAj
    vaultProtoConfig: CBcN96wCJFGDQfQbFnMxu5bPzJhKnMrNPaM3EdiQ2dLm
    vaultTokenAAccount: AwhUcFy1n9BKn4KCViJGTPd5mJZCZRfnDA3RvJN2tTne
    vaultTokenBAccount: C6jpJ1CpM4Ydd74XkKT3DkFU2L9m5U9SRtc6Hx7vXuBJ
    tokenAMint: 9DqC64JifaEmjLf6DVtNJstUiDkoTMWTP2mTjhYZFFgj
    tokenBMint: DknP44B7N8xmFRs5ZtxrraZBjXNoWdnMNTRsBQPtRQG5
    swapTokenMint: FAWxjExP1QANfos9v4yKSv7ZoMZR3aQqQ2UaZcdXmT41
    swapTokenAAccount: Cwx3LPbDg46PWX6VUD9mij617VVdCdb4KWGqqjDtmakg
    swapTokenBAccount: Dt2oxT6iFdkr16JVT8L5RuY2Vg4RPAhRSFFXPmbX7STT
    swapFeeAccount: QjhBGgJeDwmT2YGDthn9dXbe5Jj9tnJPrc6qw9jzEPa
    swapAuthority: 21MbiEm7z1bDbSFLkQ5cP9EZBmybeSSgqdVSckYTM7Si
    swap: 45poLrTDRuXJ7wbb9ydLVSsKHpVXBnGXaybV11YBste3
