environment: LOCALNET
triggerDCA:
  - vault: Dqa8zJj2Rq8ZA7zY2mnvfCBXSUNNV82f45vfnnJ736nB
    vaultProtoConfig: 3kp6nVGSaYeNpKFSYRZbAn3iePw6GChJ3vHMU2EhZ9E9
    vaultTokenAAccount: 8cYjuchfxVLUEs4mz3SvoC9ivxQ2gBVfafVuYQWQyRvo
    vaultTokenBAccount: 55kb7BNgJDxAz4siUogijfmbbn65XG7V6jzdj1UPTbD3
    tokenAMint: 4uPivsac91GH7heNkYShL31GcFVqZ47sxXDoi53DdZ8n
    tokenBMint: GFWtezJQ8CFEdFrN6AAXjGx3P5m1jENGvDqMAC1whzM3
    swapTokenMint: 3P8KWGpDPczcqvYT1eJCzvsCM8H5uk6599oumuNVGjfS
    swapTokenAAccount: Gz1kfCdyHcba3mAw9Q768pykc5SD3uAkR7mC1UEkdotM
    swapTokenBAccount: BMkM8EtBwz96LctqooF7ZCDoynvhY6yksQtuniGUDNPR
    swapFeeAccount: 5kDyDTUNkVYpBNDbTVMkWg5ApLQ92aKWqjMB6HTjzHo7
    swapAuthority: 4tNoAJ1wxKVdmTW2MxeFMAZFVaeRKddjN8hBu2rFBrUV
    swap: 6WX3BjRkvR8s764fyC9JyCr7pvwSKLJj8L7h3jh14TnE
