environment: DEVNET
triggerDCA:
  - vault: 7MQ95nLEy2HFu2uhyAwkgSvY5sKrRpwfVLT1vYZEhz2t
    vaultProtoConfig: C68mYq5zQVjwL72Ha3BriTmHDMktHNEdUNV1aYLqFfSa
    vaultTokenAAccount: BAKba1pLaCiNgcQak2bw6Es9N4TfTGoAko9BWw1TrvmV
    vaultTokenBAccount: 4S7LrB529X1s8NYphCp4d8rJJneiTNJXHxyAA7oQBpvU
    vaultTreasuryTokenBAccount: tu9f6fa3HvK4E1NCtCufTmfBdcP1bvXRNT6axnByVNQ
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 2VFEeEx9k5GVpVGvzJ3x1nLnxoNy5NDbQLoz3M78sjjX
    swapTokenMint: 8irTwMvdnVWVrNCYzo2MDumAqo4SSoe5YRK7eXNBiXMC
    swapTokenAAccount: BTp5D889NCWnGhJdxyXC1M7SsydwbNBGJBjqww9wDr6w
    swapTokenBAccount: CKm22gxRiEnUQr2QxwQ8GitwGDnS2ccrd6ruq33pZaeM
    swapFeeAccount: 9kvhHLhu5qXzawze5dhMtCBaQQVJ2TWr4zVgJUiitN7a
    swapAuthority: EUzpdbc6HKpreiPVindUMbuLoq8nBbgobtEpnVKJyJN7
    swap: HxFqKvZaJwEmbRmWwdZwbBx9sQ9tdtynbLT2kd5i6hrj
