environment: DEVNET
triggerDCA:
  - vault: DBet9km1yWwpmmEAt7jugB82RSdUUYMoPdaiJJ3v7hyc
    vaultProtoConfig: DtHWajPuD8PUFuRGqFre6vX5DhA7CB8gs4HYiLpCFxsW
    vaultTokenAAccount: Acjh1L2PxY9eWvUoYhdQRvmjtSGKryMSkyMqJ35j4ggM
    vaultTokenBAccount: 2vNvtpcx2UzCqPr34SioWS3vHimqF8fof2mCgPeMgMub
    vaultTreasuryTokenBAccount: ByShPEhFtvtCbAy6oSy9ERaHafEjs2EB9qKCMgkHCfc3
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: JD5QbPsK3nhhb1fzz5TjWRhTzwox2uUHEQXjLPjGoo1J
    swapTokenMint: 6nGCTdXH4RaheuXdFYNfJqsFx9jVinWYpAF5z2iQ9WAZ
    swapTokenAAccount: F2Hogr9eeHij88fjVVjbTCdN5eue8jgxXbxvak5VxYUN
    swapTokenBAccount: GCnhFvw4PCh9UTHtMvJsMRQZrpRj5DMF4tWarpwfoYhD
    swapFeeAccount: 2nZwK2dR5jG9RDBjj2cnqhz9YK3qAcAUs1R3EYAHx4iD
    swapAuthority: 5ry8yadABMeY5xaNqWoVXvqHKa824BvGas1FL5G2KVen
    swap: FvMWyfb112QXoupqG3egivHbhYDHbD6nLe2etfXYrUEa
