environment: DEVNET
triggerDCA:
  - vault: BBadEsT6ELWKe9dWoisX7BmA5zVcRm1JpsD9dZ1k72Sr
    vaultProtoConfig: HW94jZ3keVwmma9rs4qHRibBWesTdtHFbq13i2dGgJLn
    vaultTokenAAccount: DKepS73d6E5ckp8jQTgKYcWwKjRhdpANt6XwtCuHusPQ
    vaultTokenBAccount: FErvnoB92gxsDyHB59pvFy8gwKJt45CxZj3XC8LkvUHU
    vaultTreasuryTokenBAccount: 7WoEvrqSBPKLpEWqnrDmLKWyGcwke7LWfHsau2Riq2sN
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: JD5QbPsK3nhhb1fzz5TjWRhTzwox2uUHEQXjLPjGoo1J
    swapTokenMint: 6nGCTdXH4RaheuXdFYNfJqsFx9jVinWYpAF5z2iQ9WAZ
    swapTokenAAccount: F2Hogr9eeHij88fjVVjbTCdN5eue8jgxXbxvak5VxYUN
    swapTokenBAccount: GCnhFvw4PCh9UTHtMvJsMRQZrpRj5DMF4tWarpwfoYhD
    swapFeeAccount: 2nZwK2dR5jG9RDBjj2cnqhz9YK3qAcAUs1R3EYAHx4iD
    swapAuthority: 5ry8yadABMeY5xaNqWoVXvqHKa824BvGas1FL5G2KVen
    swap: FvMWyfb112QXoupqG3egivHbhYDHbD6nLe2etfXYrUEa
