environment: DEVNET
triggerDCA:
  - vault: 7C6tjLGLnSB1kvpKYLyYiUBxezHwrsuJKgou9FEr6Xen
    vaultProtoConfig: AC44qp8FUCQq2UcESLWNDTqNyZCYxMMRsfViDMAqVZap
    vaultTokenAAccount: 2TKk2R4LH2SAnf7nmv2K876zADHQoebzeowjReUsR4SV
    vaultTokenBAccount: 8sUJVJXhvFxqjAcKTNtY4c2TP6gin2DK1gLMCMNgfU1b
    vaultTreasuryTokenBAccount: 8Sg6oT2a3pDHTUZcSnYzCxAWQCkX2jopZHF2ciKWJFsx
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: JD5QbPsK3nhhb1fzz5TjWRhTzwox2uUHEQXjLPjGoo1J
    swapTokenMint: 6nGCTdXH4RaheuXdFYNfJqsFx9jVinWYpAF5z2iQ9WAZ
    swapTokenAAccount: F2Hogr9eeHij88fjVVjbTCdN5eue8jgxXbxvak5VxYUN
    swapTokenBAccount: GCnhFvw4PCh9UTHtMvJsMRQZrpRj5DMF4tWarpwfoYhD
    swapFeeAccount: 2nZwK2dR5jG9RDBjj2cnqhz9YK3qAcAUs1R3EYAHx4iD
    swapAuthority: 5ry8yadABMeY5xaNqWoVXvqHKa824BvGas1FL5G2KVen
    swap: FvMWyfb112QXoupqG3egivHbhYDHbD6nLe2etfXYrUEa
