environment: DEVNET
triggerDCA:
  - vault: HSpnTLryiAZVyGWyzQhdZpQ2nPVFeMrNPxs2WuyJKaB7
    vaultProtoConfig: Fypp2forr9i5LZMSjssgW15TKzSqtpyWBSTKfb9JvP9
    vaultTokenAAccount: 6eJBHjdJ6b3aomGVDYtkkAb7ZuzNWFeuipNgafeV4DaS
    vaultTokenBAccount: 63CTWTGaXHnofKqYZ8mmxX2TYQtT47sWffbXVjoBFdA8
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: FjQhx9o6uii2jJwNxYnAuvHeNYVe2meDdb9ukSoqeNqH
    swapTokenMint: 3uoLWnpfDe9ahRs4iRpZ1o5XmSnk5phfbr2iHXTnqJpq
    swapTokenAAccount: 3tYkDaEr7hEh7U5eiyUW8MAfCvjVZ76P7DoaZRu14NkQ
    swapTokenBAccount: uAfHiTqCXKqR8GHMbhG5W36GVF6E8raJEU8FLwKtGwX
    swapFeeAccount: HAie1DeaQtxdU4KAw9VPNXxrkHzq5WFFB6ibWBg9m2Wo
    swapAuthority: 8oe5D4hb6zeoMzoJDBbGDf5PWsj6CogLJmWqafRpMDGF
    swap: HJfbikSSo6s7Ebc4DMPhWSs31yeC41TTUAU4iiuXAqHA
