environment: DEVNET
triggerDCA:
  - vault: HHnwJP68CkUfmxkkdsC7vGYg1UqGBfWDvnYnFAMMjXGc
    vaultProtoConfig: 32QVuN4Qqv9fqM1Ld3xm1gK9HELbBBe6eLBvVwfzT3P5
    vaultTokenAAccount: 6NFNwDhUHVM77xDvUSi2yeT1bi1TNenDKLT4fQ74bMCF
    vaultTokenBAccount: 48LwhujAF78ror75MyLS1NeB9rVSjNmewrSpDTvsMvAY
    vaultTreasuryTokenBAccount: 6p3xzaY4N2tbgVyTYKvWntd53F5F5bPqJtvAnm33VQAV
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 2VFEeEx9k5GVpVGvzJ3x1nLnxoNy5NDbQLoz3M78sjjX
    swapTokenMint: 8irTwMvdnVWVrNCYzo2MDumAqo4SSoe5YRK7eXNBiXMC
    swapTokenAAccount: BTp5D889NCWnGhJdxyXC1M7SsydwbNBGJBjqww9wDr6w
    swapTokenBAccount: CKm22gxRiEnUQr2QxwQ8GitwGDnS2ccrd6ruq33pZaeM
    swapFeeAccount: 9kvhHLhu5qXzawze5dhMtCBaQQVJ2TWr4zVgJUiitN7a
    swapAuthority: EUzpdbc6HKpreiPVindUMbuLoq8nBbgobtEpnVKJyJN7
    swap: HxFqKvZaJwEmbRmWwdZwbBx9sQ9tdtynbLT2kd5i6hrj
