environment: DEVNET
triggerDCA:
  - vault: Hu45XJxeBYVMTqoPou7QmCvdrAKSDxeUPHzG99LEH8cd
    vaultProtoConfig: 9X5X1wNP7nQkfHMi8ZLc7hSMCSrpmVFPWsHVLH17dXMG
    vaultTokenAAccount: GZ1EF61g6x73oF9KCaJMbtoxM8SLY6WdqRbwTayHKZT5
    vaultTokenBAccount: 8shkkhpkhdgfjf5BiP6vtza3nPJXsmioArsA4rQDQTmP
    vaultTreasuryTokenBAccount: 2am9SCKwjDrGrJQSc6oTmgkCMPerrnTdyxFycQp9ppDD
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: BVdu2YA1RfUvfKQbLSgQfa8e9AygBkrUpHyg771kaXGE
    swapTokenMint: 9eJKJwTEUVvqU7BZo36Ya5zn4ZKP56uABA3x345P7jsW
    swapTokenAAccount: J1qtTEZVmvvmR8m1W3ziRbEgmtDLeicLy7Z9VT7UZCU
    swapTokenBAccount: HJGG4XMwqtQfUakg3DMqiLsr3keEw4BF2XHXjEedqvc2
    swapFeeAccount: 5bYFhxb2wbfNTCGQZgJLYgg1mC8JGMQun87Z65ahK5Ci
    swapAuthority: 9mRQ7JuWdQGfKt5HnvDHKkAtWMQt2FmbwJJ6oBG2qcwC
    swap: 3SxK778tKf96NkG5FKeXJ2krcUSC2dUZXJqF9dz46dWt
