environment: DEVNET
triggerDCA:
  - vault: 7ZtxVqjFRfvhqfWzNrp2zUzwmTVTsK34YhhgL146HPWc
    vaultProtoConfig: 8Q8oKRa5ky2gWK9xkS7yBwtcaoG5E8a4CxJjeA4kha9s
    vaultTokenAAccount: GcGBpgkbMGUya695UKAdHz3NXTdvgw7XoTcYh6bmJ2oN
    vaultTokenBAccount: 2zNLACiT5o2C597byXDjwxuvtDaH7i6XWbHM8S3L9e3X
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: HjzNr3kHnWv2iLbq79eqkCvnYZ5eGAXtnhske9AxnhV
    swapTokenMint: 3PNuVomHRSkVMGsoJVJmvi8sS1JVJPJTniwQDmjZeVoA
    swapTokenAAccount: EPtTFVwatpgQQfWvLhnqZEAKunoY7sUuX1HdVcDbz7BV
    swapTokenBAccount: Bo4WBxJmnGjUSnYvhfdphVK6aQCVJAKL6cuvM8a3BhxT
    swapFeeAccount: F2rHeX3zc1AvpcyWKd1G27euqfZWSLFfxNe2zH4Sv4Yr
    swapAuthority: AtvxrP2N31bEsnTZiwuHBGkBW8aGv4mdM4j7hUpjkUst
    swap: EjrJVMjUx2vFjG4GQvrjuJ2L6TojnVkdKWQ2QbhidnL3
