environment: DEVNET
triggerDCA:
  - vault: B8FYKw5REb5mqTtbKn6XPxWXVyBJzcdN2nQD3UvLN3pV
    vaultProtoConfig: 7NrVYssWrPbB7KSaeewBsCMNDatXHEUa11rZAq6pftpJ
    vaultTokenAAccount: 7LGoLTs3m9qVgUjoGg2NLuNeZU5Vh8at2mEzjnPrqgQG
    vaultTokenBAccount: 7A93YsbDkCyaZ7EUcQCVpNJfUK4sstVnvJ65P81rD6qw
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: FjQhx9o6uii2jJwNxYnAuvHeNYVe2meDdb9ukSoqeNqH
    swapTokenMint: 3uoLWnpfDe9ahRs4iRpZ1o5XmSnk5phfbr2iHXTnqJpq
    swapTokenAAccount: 3tYkDaEr7hEh7U5eiyUW8MAfCvjVZ76P7DoaZRu14NkQ
    swapTokenBAccount: uAfHiTqCXKqR8GHMbhG5W36GVF6E8raJEU8FLwKtGwX
    swapFeeAccount: HAie1DeaQtxdU4KAw9VPNXxrkHzq5WFFB6ibWBg9m2Wo
    swapAuthority: 8oe5D4hb6zeoMzoJDBbGDf5PWsj6CogLJmWqafRpMDGF
    swap: HJfbikSSo6s7Ebc4DMPhWSs31yeC41TTUAU4iiuXAqHA
