environment: DEVNET
triggerDCA:
  - vault: ASWLY5gLVh59U6d1SYGZjj559Fa2J79zXhtZ2evQjwqd
    vaultProtoConfig: Dy9BiV3HVFuMemZ5G1hwS5yusHYsYkEynVRzuSytkBSa
    vaultTokenAAccount: 2ZgCgopnavwM2LRA5VvkMuFhVfLVbC4tG4tQLCtDeCZy
    vaultTokenBAccount: HHHpZXbW1US48teced911tpZFQE5A9H8S3exVnfwsPrj
    vaultTreasuryTokenBAccount: NgTqqz9tFh36v1DUY2S4DaTArvMP6AE9E1zRTerUR1s
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 8uCHB1gSPFg18dMmmSVhQ5HChAiAy66tdf8bZP4HtupH
    swapTokenMint: BNTkPDYGm5rL6YnzVM85oGwFZF4cMghasa3CVp348Tbv
    swapTokenAAccount: 5SbmTBWmZYBn6Y5T9w6buE5aQmpzDPTgavTj1fz1qFcX
    swapTokenBAccount: G3K9SMLp6p24dT9PdzigcZR9dHYZ2km8V24bQrqG4qN8
    swapFeeAccount: AV2HQSFrmviR3Yx7qPonXzmUy3re2hsEd8A7bCCCtGmD
    swapAuthority: DzYiL4enuTJyuW1hy6wAxpreog4KghVYbGKhJoaxGMYK
    swap: GpR9u1PkVKUKhCG52BGPbs8K25ksfXwaRTcQmdjco5Lr
