environment: DEVNET
triggerDCA:
  - vault: 4c7qinQpFpGYtK7YFg6hfiPPsvu7WStr3au5gZiaV7ye
    vaultProtoConfig: BYvnVLnnLfHfMdiU3xyRbcovTtjZSX7jMVbL4uCWgNYm
    vaultTokenAAccount: EoJFGQAGpECLqRPcQcDVHgLQsX96axBN1GyZhody6C6s
    vaultTokenBAccount: 2vAjyCFsxst8m7c8VSQeXHyepkquBBmFHcJSbAvTaaPu
    vaultTreasuryTokenBAccount: CKCYxucREWmQ1teYS82bSYK1VmsqfhacG2tVQm3przog
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 2VFEeEx9k5GVpVGvzJ3x1nLnxoNy5NDbQLoz3M78sjjX
    swapTokenMint: 8irTwMvdnVWVrNCYzo2MDumAqo4SSoe5YRK7eXNBiXMC
    swapTokenAAccount: BTp5D889NCWnGhJdxyXC1M7SsydwbNBGJBjqww9wDr6w
    swapTokenBAccount: CKm22gxRiEnUQr2QxwQ8GitwGDnS2ccrd6ruq33pZaeM
    swapFeeAccount: 9kvhHLhu5qXzawze5dhMtCBaQQVJ2TWr4zVgJUiitN7a
    swapAuthority: EUzpdbc6HKpreiPVindUMbuLoq8nBbgobtEpnVKJyJN7
    swap: HxFqKvZaJwEmbRmWwdZwbBx9sQ9tdtynbLT2kd5i6hrj
