environment: DEVNET
triggerDCA:
  - vault: 8ZLcKLpZxPxnnL7r3DNkJ1CLs3ha8BMKtRiAPsr3wLjm
    vaultProtoConfig: G58uMtpKA6kuZ7M2xqnb1YShQCVYyq4FX6F8ixm5nvip
    vaultTokenAAccount: GCCn4Zr5iuThGGKgZE4yuW5w9AdGRv4iXMuCd7NVCWvu
    vaultTokenBAccount: 6eg864XbmffKoCt6DFqpWUhPTjxuLgodVbWsd565vaxF
    vaultTreasuryTokenBAccount: D6Zuvi9Zm2i3DP2PQwZUxLLHdfKLYkuzkteecEiL5XDo
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 2VFEeEx9k5GVpVGvzJ3x1nLnxoNy5NDbQLoz3M78sjjX
    swapTokenMint: 8irTwMvdnVWVrNCYzo2MDumAqo4SSoe5YRK7eXNBiXMC
    swapTokenAAccount: BTp5D889NCWnGhJdxyXC1M7SsydwbNBGJBjqww9wDr6w
    swapTokenBAccount: CKm22gxRiEnUQr2QxwQ8GitwGDnS2ccrd6ruq33pZaeM
    swapFeeAccount: 9kvhHLhu5qXzawze5dhMtCBaQQVJ2TWr4zVgJUiitN7a
    swapAuthority: EUzpdbc6HKpreiPVindUMbuLoq8nBbgobtEpnVKJyJN7
    swap: HxFqKvZaJwEmbRmWwdZwbBx9sQ9tdtynbLT2kd5i6hrj
