environment: DEVNET
triggerDCA:
  - vault: 7sgH284pm7dgtVdeWxW9pjuJWnLjuWG5iRUC9PAgV3Ls
    vaultProtoConfig: 31bMdYE7bVzbUnE7XW5FjkHsSE659z6zrUFroMWSSYKu
    vaultTokenAAccount: 6az9pSuJnkpy3wxnzMsiAwPZ8tfa83SDYzLk6qT5BSDj
    vaultTokenBAccount: 97MU6FgURnELK4MEWAJ9Jtx4Lnpb7Z1wsr1ETmH88VhA
    vaultTreasuryTokenBAccount: EQUWJtc8rfk1qYqZ8zwJqqQKa4LN1zBBW9hPFxfxrhHo
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 8uCHB1gSPFg18dMmmSVhQ5HChAiAy66tdf8bZP4HtupH
    swapTokenMint: BNTkPDYGm5rL6YnzVM85oGwFZF4cMghasa3CVp348Tbv
    swapTokenAAccount: 5SbmTBWmZYBn6Y5T9w6buE5aQmpzDPTgavTj1fz1qFcX
    swapTokenBAccount: G3K9SMLp6p24dT9PdzigcZR9dHYZ2km8V24bQrqG4qN8
    swapFeeAccount: AV2HQSFrmviR3Yx7qPonXzmUy3re2hsEd8A7bCCCtGmD
    swapAuthority: DzYiL4enuTJyuW1hy6wAxpreog4KghVYbGKhJoaxGMYK
    swap: GpR9u1PkVKUKhCG52BGPbs8K25ksfXwaRTcQmdjco5Lr
