environment: DEVNET
triggerDCA:
  - vault: AGq4rcfFxaxzAhBVwCUSxccxNFVRG8R6J7D3Dfbg977N
    vaultProtoConfig: 6VVpp3vSsexBhoTHph7adfYfyVshs7BcgBV7jWqTV4p6
    vaultTokenAAccount: 3CpfHMpLcSPywrcNVMis91XRsrhbyNLV6KWx1k7Ebhxs
    vaultTokenBAccount: 99nqoRsQBzP1gYQ6vPoG1PJwQQRtCbMFL7Hh5jSNL3HK
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: HjzNr3kHnWv2iLbq79eqkCvnYZ5eGAXtnhske9AxnhV
    swapTokenMint: 3PNuVomHRSkVMGsoJVJmvi8sS1JVJPJTniwQDmjZeVoA
    swapTokenAAccount: EPtTFVwatpgQQfWvLhnqZEAKunoY7sUuX1HdVcDbz7BV
    swapTokenBAccount: Bo4WBxJmnGjUSnYvhfdphVK6aQCVJAKL6cuvM8a3BhxT
    swapFeeAccount: F2rHeX3zc1AvpcyWKd1G27euqfZWSLFfxNe2zH4Sv4Yr
    swapAuthority: AtvxrP2N31bEsnTZiwuHBGkBW8aGv4mdM4j7hUpjkUst
    swap: EjrJVMjUx2vFjG4GQvrjuJ2L6TojnVkdKWQ2QbhidnL3
