environment: DEVNET
triggerDCA:
  - vault: 5tDxLVndrEiRKfuGwHF2DJvjpYGiWtmBrcFYW3CESkw9
    vaultProtoConfig: HGwk58HwBrYMVaUMVBz4PQzCJwhwUhAmoetTueLvtCh1
    vaultTokenAAccount: A1Vx1vAgLqrEiVivWX5vJcoXv3uGSwcUcW7odp7rMStz
    vaultTokenBAccount: EYFmto5NsGSLPJDpWaLgMeKY1yNkp6cbUpoQ9NM7b4nW
    vaultTreasuryTokenBAccount: G4V76vQDUZeSsUqt71cQurnop66RZ6E2FWAiASeQcTob
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 8uCHB1gSPFg18dMmmSVhQ5HChAiAy66tdf8bZP4HtupH
    swapTokenMint: BNTkPDYGm5rL6YnzVM85oGwFZF4cMghasa3CVp348Tbv
    swapTokenAAccount: 5SbmTBWmZYBn6Y5T9w6buE5aQmpzDPTgavTj1fz1qFcX
    swapTokenBAccount: G3K9SMLp6p24dT9PdzigcZR9dHYZ2km8V24bQrqG4qN8
    swapFeeAccount: AV2HQSFrmviR3Yx7qPonXzmUy3re2hsEd8A7bCCCtGmD
    swapAuthority: DzYiL4enuTJyuW1hy6wAxpreog4KghVYbGKhJoaxGMYK
    swap: GpR9u1PkVKUKhCG52BGPbs8K25ksfXwaRTcQmdjco5Lr
