environment: DEVNET
triggerDCA:
  - vault: 7Exb2GKGZexpjiyTTUvZhDRjg2FistRpfcYkStKTZ5im
    vaultProtoConfig: 2ya8THp5EKbtbNET8Fef8i82D63i6bUMBFfR88DdCRue
    vaultTokenAAccount: 9HQUGKMd7m689Ny44kV2tP6ZCBPczcX2BPQgyAqMVAsj
    vaultTokenBAccount: C1j4seohAqsdib9WN1SF39F1uHn5cb36sg6dPxSpAGYa
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: BAUM12vtxFLRc1zTtUedY4ca62pndaLpD58oXjCJDK2F
    swapTokenMint: 9pvQzhnV1E9uG1iUuN8xjemzh1gAxJRKAeDLpXXLjV4g
    swapTokenAAccount: 9KQqmoA2iECctKVgEoANxCUcx5PDaXYeNLJYGfr1o6KF
    swapTokenBAccount: 7erZmzn1kFEQwR2vDevv91cQ5N1fVRsdtqHi2YoUnM4e
    swapFeeAccount: 3BzR4mgyRU56Q86hR3a8XUtWdhSjSUYMFVLj2VdsJZc4
    swapAuthority: DHWSX8zUsDy4CyFfEr7uVqeF4CFqgnwu5fgnu4D1wco7
    swap: 6iwist9N3MvcpDU1QT4phBGqZXc7nY6dUPq7tsCWfFuS
