environment: DEVNET
triggerDCA:
  - vault: DzxR5agoHk3FT2SxZ7veWGR1pqkWZb4FpFrQswbkqzFB
    vaultProtoConfig: 7ZQMuGB6odU6JwBST6fnRZU2iVrMrXFumQtsYibmvgeB
    vaultTokenAAccount: 4fnEQKDiyvy1iKFYDz9AGpoRFdoNJ7JnDig458Trnui8
    vaultTokenBAccount: Vc1RRqgF6z8Kcfwk4ckWCNmeL8iWGaRNAnbNjVyNSEf
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: HjzNr3kHnWv2iLbq79eqkCvnYZ5eGAXtnhske9AxnhV
    swapTokenMint: 3PNuVomHRSkVMGsoJVJmvi8sS1JVJPJTniwQDmjZeVoA
    swapTokenAAccount: EPtTFVwatpgQQfWvLhnqZEAKunoY7sUuX1HdVcDbz7BV
    swapTokenBAccount: Bo4WBxJmnGjUSnYvhfdphVK6aQCVJAKL6cuvM8a3BhxT
    swapFeeAccount: F2rHeX3zc1AvpcyWKd1G27euqfZWSLFfxNe2zH4Sv4Yr
    swapAuthority: AtvxrP2N31bEsnTZiwuHBGkBW8aGv4mdM4j7hUpjkUst
    swap: EjrJVMjUx2vFjG4GQvrjuJ2L6TojnVkdKWQ2QbhidnL3
