environment: DEVNET
triggerDCA:
  - vault: 6NE5BVVtVkRerr7ScZ62MJtZRrUx8aE4TeuGLfAFLCns
    vaultProtoConfig: Cs853UZSp14zncYRi7BSMhEWtH4gQgmTHuZfveyVbNS1
    vaultTokenAAccount: ELbUAZtzCB2bafpXznaDV5yD1tQ2iBN3sXLc4w8CAkLw
    vaultTokenBAccount: D29ejj4Hj1agZpwCYyixz74z7Jir1PXXR6vBT5ShoNyy
    vaultTreasuryTokenBAccount: 7tvE6SDFQfWQrdves8YjHnzTkDWqRkvgmivyi1annrp2
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: JD5QbPsK3nhhb1fzz5TjWRhTzwox2uUHEQXjLPjGoo1J
    swapTokenMint: 6nGCTdXH4RaheuXdFYNfJqsFx9jVinWYpAF5z2iQ9WAZ
    swapTokenAAccount: F2Hogr9eeHij88fjVVjbTCdN5eue8jgxXbxvak5VxYUN
    swapTokenBAccount: GCnhFvw4PCh9UTHtMvJsMRQZrpRj5DMF4tWarpwfoYhD
    swapFeeAccount: 2nZwK2dR5jG9RDBjj2cnqhz9YK3qAcAUs1R3EYAHx4iD
    swapAuthority: 5ry8yadABMeY5xaNqWoVXvqHKa824BvGas1FL5G2KVen
    swap: FvMWyfb112QXoupqG3egivHbhYDHbD6nLe2etfXYrUEa
