environment: DEVNET
triggerDCA:
  - vault: 5WA7rRLzP1jep22e8AjDd5kfLnCJiyRfUypPrqDDf8iC
    vaultProtoConfig: 2TKpHS8wGQFH7K9Yyj36vQga24oggddJj1sKPjvUptRY
    vaultTokenAAccount: 6M2fjUmrzQCWxrUoX6Q3bCPeke8VL62bz3VjEeN2Fyv3
    vaultTokenBAccount: FN8H2VzW5NzQk3kLtm3mEkkugfnmwk8jKVWqFRUvaxTV
    vaultTreasuryTokenBAccount: 34TY2yEvBxA2Yp7pKYRYQJE31vPmtrB4rN2nS8LEr2H5
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: JD5QbPsK3nhhb1fzz5TjWRhTzwox2uUHEQXjLPjGoo1J
    swapTokenMint: 6nGCTdXH4RaheuXdFYNfJqsFx9jVinWYpAF5z2iQ9WAZ
    swapTokenAAccount: F2Hogr9eeHij88fjVVjbTCdN5eue8jgxXbxvak5VxYUN
    swapTokenBAccount: GCnhFvw4PCh9UTHtMvJsMRQZrpRj5DMF4tWarpwfoYhD
    swapFeeAccount: 2nZwK2dR5jG9RDBjj2cnqhz9YK3qAcAUs1R3EYAHx4iD
    swapAuthority: 5ry8yadABMeY5xaNqWoVXvqHKa824BvGas1FL5G2KVen
    swap: FvMWyfb112QXoupqG3egivHbhYDHbD6nLe2etfXYrUEa
