environment: DEVNET
triggerDCA:
  - vault: DuvnTqhWGqy39AvGhCBeijHxpmqsEwbzJV9YEFYP152H
    vaultProtoConfig: BjJ4e6MwtL3Aoz9K5bWyTTpsqKefmRX3fZ9C9by9EDtc
    vaultTokenAAccount: 79SXSjJxVHAEEQTt2qnazYZZ3GcWgKFLyHLpC4hs6JBJ
    vaultTokenBAccount: CxqQrcobrVGFx2yAN9h5oh4h7oau74U2chxJNAjcRMoQ
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: BACh99A1k6vSoCYZFvFaZ637Dk3hm9XDAr5fAZSVktst
    swapTokenMint: 8Com5s5u4Bpo5gnejnAvhgyNCZLSPDvGYeZdUen2ZYjk
    swapTokenAAccount: HFfRYpgcrXgtQFpwXjk1y2DGQzddNmPmonahLBt6tZbt
    swapTokenBAccount: 7hxTyUyYSCsv3QmtabT2VFhyvbmFu3Yq43xn8m2fxXZb
    swapFeeAccount: 5GNb5u8VWwhvbTyv9AVvF73Egzk2VzR3PXknrixjwmct
    swapAuthority: 8knGHuXTJPTUuBmRNN6tDfpfYBVAAV8iWSkHXrqNbGPL
    swap: FoXCCt1dYSpuY6ixhQco59CvsTnVuE7YTVwXNaQhCzcH
