environment: DEVNET
triggerDCA:
  - vault: 4fmhcd45VCR7tK32q1xiHQWQi1o12558mbpNxZpFtMio
    vaultProtoConfig: HXUoriszU5oveBtNRuWySFHQyu18c1upxNYNMTSoQVfx
    vaultTokenAAccount: 7UGBoBb4zYdUWttMKw95yQdmSrLgfcGGTvtPjDs8r4gQ
    vaultTokenBAccount: 4hwHiNcpyz7Brjaf6DR29MvjuoEUSao1yM5bpeE1Bfbz
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: BAUM12vtxFLRc1zTtUedY4ca62pndaLpD58oXjCJDK2F
    swapTokenMint: 9pvQzhnV1E9uG1iUuN8xjemzh1gAxJRKAeDLpXXLjV4g
    swapTokenAAccount: 9KQqmoA2iECctKVgEoANxCUcx5PDaXYeNLJYGfr1o6KF
    swapTokenBAccount: 7erZmzn1kFEQwR2vDevv91cQ5N1fVRsdtqHi2YoUnM4e
    swapFeeAccount: 3BzR4mgyRU56Q86hR3a8XUtWdhSjSUYMFVLj2VdsJZc4
    swapAuthority: DHWSX8zUsDy4CyFfEr7uVqeF4CFqgnwu5fgnu4D1wco7
    swap: 6iwist9N3MvcpDU1QT4phBGqZXc7nY6dUPq7tsCWfFuS
