environment: DEVNET
triggerDCA:
  - vault: AUjgecXYWP6xEaHDpBuVisgCzKDY8nfH9HX9GEJTPaZt
    vaultProtoConfig: 98WpFtc3e6coKdDNY4ESTXNiPprhuDPvX1z677Y81yy4
    vaultTokenAAccount: gbb1Qd4nkKzxifR4gztaaCFKs1zKZina3PNxEoEwYXd
    vaultTokenBAccount: 2Eh9DsVxNSiQGiapWXh3qhwTPuCt73NuB8H7YxNmnhLE
    vaultTreasuryTokenBAccount: DN1SG2aeh3oyFRZwKQkpvJErvqxmtm3z89MCNQX3tHo5
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 7i4JAYu8GCGbFyiTrmjvJ68Q7WLN54y4r8F1KKdQRPma
    swapTokenMint: CrdocLxKTvPGHoi84krfsre3EcfcrHsgM9E2PFVGVGw4
    swapTokenAAccount: 2hZzp8EWjDPJzQS4jPRn4wt5fGJ2zpgaNRpBxFsymHHw
    swapTokenBAccount: H7ZiL93JPFPybAVrC74zPcwXrMkPRcADqAoHvMuPN92N
    swapFeeAccount: 51Wy5gKDKNngMQh5hxELmku4H8JeUwXcdKpbL2LbssX
    swapAuthority: J8e8N6V531nnRPzdiQTcneyeyv5AcVqrxQhHCiQKkQo6
    swap: APeTSKEryyKNYXc5ZHBtzNJhX4eLTBN9toQbL3sXVGCm
