environment: DEVNET
triggerDCA:
  - vault: 3ZQvDRWHF631imYrMYmeetFuET3vobNXJvNgThmNpA9o
    vaultProtoConfig: 3e9aJzTJNWut6jmkrSXxPtu3XFoKfJj4iFEJBo45cNza
    vaultTokenAAccount: 5nBpDU7uu93mCZSnNNGFaZFJsE79hdh1kk3J7VLH1FMS
    vaultTokenBAccount: 5E3A1VfuKu5CuA35fp1gGqtpR3jM7ANRvKnkpgCWjyU7
    vaultTreasuryTokenBAccount: HwaR38gjVmyHc8zgZQtbYatR7E3YQ4GbKUCewmGvWymo
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: BVdu2YA1RfUvfKQbLSgQfa8e9AygBkrUpHyg771kaXGE
    swapTokenMint: 9eJKJwTEUVvqU7BZo36Ya5zn4ZKP56uABA3x345P7jsW
    swapTokenAAccount: J1qtTEZVmvvmR8m1W3ziRbEgmtDLeicLy7Z9VT7UZCU
    swapTokenBAccount: HJGG4XMwqtQfUakg3DMqiLsr3keEw4BF2XHXjEedqvc2
    swapFeeAccount: 5bYFhxb2wbfNTCGQZgJLYgg1mC8JGMQun87Z65ahK5Ci
    swapAuthority: 9mRQ7JuWdQGfKt5HnvDHKkAtWMQt2FmbwJJ6oBG2qcwC
    swap: 3SxK778tKf96NkG5FKeXJ2krcUSC2dUZXJqF9dz46dWt
