environment: DEVNET
triggerDCA:
  - vault: 8A2uN8rNhJdsfVxmqQqXB49L96BzDhJU2Muo5sYzgHPm
    vaultProtoConfig: F6NcYCTZGWBSZMbfLrngCoFY3eJYcP83D73JQ5VHochR
    vaultTokenAAccount: 3amfr5opCEo2FTn68jvcwuViUmRRwABExZPEAZqpV2J6
    vaultTokenBAccount: 4K7SwA8WdKSAL1dEVDuLswbWG733wXbPZNxAikBMAqyd
    vaultTreasuryTokenBAccount: C3NywFino7rRf229YimwWNghoKa24vRyUP9HBEEAjj4R
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: BVdu2YA1RfUvfKQbLSgQfa8e9AygBkrUpHyg771kaXGE
    swapTokenMint: 9eJKJwTEUVvqU7BZo36Ya5zn4ZKP56uABA3x345P7jsW
    swapTokenAAccount: J1qtTEZVmvvmR8m1W3ziRbEgmtDLeicLy7Z9VT7UZCU
    swapTokenBAccount: HJGG4XMwqtQfUakg3DMqiLsr3keEw4BF2XHXjEedqvc2
    swapFeeAccount: 5bYFhxb2wbfNTCGQZgJLYgg1mC8JGMQun87Z65ahK5Ci
    swapAuthority: 9mRQ7JuWdQGfKt5HnvDHKkAtWMQt2FmbwJJ6oBG2qcwC
    swap: 3SxK778tKf96NkG5FKeXJ2krcUSC2dUZXJqF9dz46dWt
