environment: DEVNET
triggerDCA:
  - vault: 63WjPLWGirghDvpGzreVpWQd7PPCwZz1RmNFer6SPufA
    vaultProtoConfig: 5pymzn5V6FHg8W7ZYyYi2dtv9onKCT3wvMtYfQncLUef
    vaultTokenAAccount: 5UwAsnDNiJgFMDiaxVHgLs5siHqzApvHSNpDWYSfws2n
    vaultTokenBAccount: 98wFFCGsPLp8ELxmQuc1mgEUvuSHaGmcb5Rx44YPDs6q
    vaultTreasuryTokenBAccount: 3sDJvjZtGfZj2BwBV14tgHh5nJ27sB4k7bd4nxnvWrfF
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: BVdu2YA1RfUvfKQbLSgQfa8e9AygBkrUpHyg771kaXGE
    swapTokenMint: 9eJKJwTEUVvqU7BZo36Ya5zn4ZKP56uABA3x345P7jsW
    swapTokenAAccount: J1qtTEZVmvvmR8m1W3ziRbEgmtDLeicLy7Z9VT7UZCU
    swapTokenBAccount: HJGG4XMwqtQfUakg3DMqiLsr3keEw4BF2XHXjEedqvc2
    swapFeeAccount: 5bYFhxb2wbfNTCGQZgJLYgg1mC8JGMQun87Z65ahK5Ci
    swapAuthority: 9mRQ7JuWdQGfKt5HnvDHKkAtWMQt2FmbwJJ6oBG2qcwC
    swap: 3SxK778tKf96NkG5FKeXJ2krcUSC2dUZXJqF9dz46dWt
