environment: DEVNET
triggerDCA:
  - vault: C3dfTLo5eCRUHphu2oPVEi2j75pUaP7YyLLqdtWTc6ef
    vaultProtoConfig: 2whP89acn7LKS9WcdH17jbzJv22unwGAHu7Qd1Ua6bEm
    vaultTokenAAccount: HEjnFppv2xkBT7nMacuxVb6BfNtaPdbjGSqy73E3T7Sr
    vaultTokenBAccount: 2n7t33wuQ3jBA36dnJU6VLd5pkjJcRc8fSVwxo6ANFtP
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: BAUM12vtxFLRc1zTtUedY4ca62pndaLpD58oXjCJDK2F
    swapTokenMint: 9pvQzhnV1E9uG1iUuN8xjemzh1gAxJRKAeDLpXXLjV4g
    swapTokenAAccount: 9KQqmoA2iECctKVgEoANxCUcx5PDaXYeNLJYGfr1o6KF
    swapTokenBAccount: 7erZmzn1kFEQwR2vDevv91cQ5N1fVRsdtqHi2YoUnM4e
    swapFeeAccount: 3BzR4mgyRU56Q86hR3a8XUtWdhSjSUYMFVLj2VdsJZc4
    swapAuthority: DHWSX8zUsDy4CyFfEr7uVqeF4CFqgnwu5fgnu4D1wco7
    swap: 6iwist9N3MvcpDU1QT4phBGqZXc7nY6dUPq7tsCWfFuS
