environment: DEVNET
triggerDCA:
  - vault: 8BJRvjHpo7tVnKrWpnuEi8kfQEWuppJrhMudjDVUHxun
    vaultProtoConfig: 3cAMy1wK3a1RcugmvjGpep8wNj7UyhZjkBxQVgVJZs37
    vaultTokenAAccount: nk4LeVaybCc2AvFUVxhjEF1wNaxRPU9btvG2dAmLVWK
    vaultTokenBAccount: 4f892UudodvJeiNtj5guXgu1Y3Y5tbdDEaB4DQA8w9fm
    vaultTreasuryTokenBAccount: F8XjJTAs2SsmDKJoxNRzrtZtDsU4v1w1WPnMw7uShs2Q
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 7i4JAYu8GCGbFyiTrmjvJ68Q7WLN54y4r8F1KKdQRPma
    swapTokenMint: CrdocLxKTvPGHoi84krfsre3EcfcrHsgM9E2PFVGVGw4
    swapTokenAAccount: 2hZzp8EWjDPJzQS4jPRn4wt5fGJ2zpgaNRpBxFsymHHw
    swapTokenBAccount: H7ZiL93JPFPybAVrC74zPcwXrMkPRcADqAoHvMuPN92N
    swapFeeAccount: 51Wy5gKDKNngMQh5hxELmku4H8JeUwXcdKpbL2LbssX
    swapAuthority: J8e8N6V531nnRPzdiQTcneyeyv5AcVqrxQhHCiQKkQo6
    swap: APeTSKEryyKNYXc5ZHBtzNJhX4eLTBN9toQbL3sXVGCm
