environment: DEVNET
triggerDCA:
  - vault: 3avVoJgThZqv7eHHomdaee4QomeJVcJAhGggthZuNYTL
    vaultProtoConfig: 3E5nGAAK1CheybTdaxLeSCsbbpmMBpVKwNJEhfe4dD9q
    vaultTokenAAccount: 5sjAPXfJjHoja57ojyzfMdBGeM8TwwsYymCk24wYEuS9
    vaultTokenBAccount: A2K5vp6KAYgToV5LRHMXRa9oDuNTyC9wL9MWQTV8S2YQ
    vaultTreasuryTokenBAccount: FV3iqWzxjk8erpv2f4WazNR25tceF7fHoJkho4HEbf6W
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 8uCHB1gSPFg18dMmmSVhQ5HChAiAy66tdf8bZP4HtupH
    swapTokenMint: BNTkPDYGm5rL6YnzVM85oGwFZF4cMghasa3CVp348Tbv
    swapTokenAAccount: 5SbmTBWmZYBn6Y5T9w6buE5aQmpzDPTgavTj1fz1qFcX
    swapTokenBAccount: G3K9SMLp6p24dT9PdzigcZR9dHYZ2km8V24bQrqG4qN8
    swapFeeAccount: AV2HQSFrmviR3Yx7qPonXzmUy3re2hsEd8A7bCCCtGmD
    swapAuthority: DzYiL4enuTJyuW1hy6wAxpreog4KghVYbGKhJoaxGMYK
    swap: GpR9u1PkVKUKhCG52BGPbs8K25ksfXwaRTcQmdjco5Lr
