environment: DEVNET
triggerDCA:
  - vault: ARAfrcRG9VzYuZfsYbiTbEmj2kjQ4e8HiDuXSeAzZg6t
    vaultProtoConfig: Fvvsm2ZrBqJSA12pNRarhpNqeKptgVcrCm2Kvw1kjipL
    vaultTokenAAccount: 6xFSN17thwDe5CQqYVRJsHYp27S6sMTf2YtdZSmiojLQ
    vaultTokenBAccount: ggjELSQkCjiWVRb4XC9ZPUXgnyE3nmwhZBavCpyAdsP
    vaultTreasuryTokenBAccount: HZzDexgYtG5VkTdFWXnD1XjKBbZRM465R5hMpS2pY9Ld
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 7i4JAYu8GCGbFyiTrmjvJ68Q7WLN54y4r8F1KKdQRPma
    swapTokenMint: CrdocLxKTvPGHoi84krfsre3EcfcrHsgM9E2PFVGVGw4
    swapTokenAAccount: 2hZzp8EWjDPJzQS4jPRn4wt5fGJ2zpgaNRpBxFsymHHw
    swapTokenBAccount: H7ZiL93JPFPybAVrC74zPcwXrMkPRcADqAoHvMuPN92N
    swapFeeAccount: 51Wy5gKDKNngMQh5hxELmku4H8JeUwXcdKpbL2LbssX
    swapAuthority: J8e8N6V531nnRPzdiQTcneyeyv5AcVqrxQhHCiQKkQo6
    swap: APeTSKEryyKNYXc5ZHBtzNJhX4eLTBN9toQbL3sXVGCm
