environment: DEVNET
triggerDCA:
  - vault: 6r5Umf7Q9s6DeNkWnEzN3zi984o35WEb4qnpa3LNLC8s
    vaultProtoConfig: GFybtbs2TXvsgkYdbH5RoWNqvJauCkders26vCR6Tp7b
    vaultTokenAAccount: GXizhJ4djnbUFLvrbMCTzePEkPfK1tdDV5XR3fMC8gUQ
    vaultTokenBAccount: 65yQuacZQ93aXJf7MVWihDSrD7i5q9AdV3dhQ2NQxZyA
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: FjQhx9o6uii2jJwNxYnAuvHeNYVe2meDdb9ukSoqeNqH
    swapTokenMint: 3uoLWnpfDe9ahRs4iRpZ1o5XmSnk5phfbr2iHXTnqJpq
    swapTokenAAccount: 3tYkDaEr7hEh7U5eiyUW8MAfCvjVZ76P7DoaZRu14NkQ
    swapTokenBAccount: uAfHiTqCXKqR8GHMbhG5W36GVF6E8raJEU8FLwKtGwX
    swapFeeAccount: HAie1DeaQtxdU4KAw9VPNXxrkHzq5WFFB6ibWBg9m2Wo
    swapAuthority: 8oe5D4hb6zeoMzoJDBbGDf5PWsj6CogLJmWqafRpMDGF
    swap: HJfbikSSo6s7Ebc4DMPhWSs31yeC41TTUAU4iiuXAqHA
