environment: DEVNET
triggerDCA:
  - vault: 7Pne15s8NpYBPwPKYcHHjfUDURCyXfDt5ZdKnqReiXXS
    vaultProtoConfig: 5Vg4z8YfKSNin3QyfT4AXVKbm8wrQjVKXWf2iWFgVKN5
    vaultTokenAAccount: CHfBGMjX4emjjgczj7M9XHwHxbiqq3pRkuxW8m4c5JHj
    vaultTokenBAccount: GobG39R6U4aSqLzJ8vHR1kCPU2mq7edZ3mdjWwzynpmF
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: HjzNr3kHnWv2iLbq79eqkCvnYZ5eGAXtnhske9AxnhV
    swapTokenMint: 3PNuVomHRSkVMGsoJVJmvi8sS1JVJPJTniwQDmjZeVoA
    swapTokenAAccount: EPtTFVwatpgQQfWvLhnqZEAKunoY7sUuX1HdVcDbz7BV
    swapTokenBAccount: Bo4WBxJmnGjUSnYvhfdphVK6aQCVJAKL6cuvM8a3BhxT
    swapFeeAccount: F2rHeX3zc1AvpcyWKd1G27euqfZWSLFfxNe2zH4Sv4Yr
    swapAuthority: AtvxrP2N31bEsnTZiwuHBGkBW8aGv4mdM4j7hUpjkUst
    swap: EjrJVMjUx2vFjG4GQvrjuJ2L6TojnVkdKWQ2QbhidnL3
