environment: DEVNET
triggerDCA:
  - vault: 6o9GXr8yEJibkKRAnUM4SxWvoZD993ZgugAeR8hYee5e
    vaultProtoConfig: 5LfEefz3pLmHE1GMjE925g2tbwCt5yLM1FaV2Svg7pAn
    vaultTokenAAccount: 4f7stfMDwHLs3qudvj2aCCXcjfLbessEFfXUqEhpQPPU
    vaultTokenBAccount: H7a5eaQV8AcsUbK6JRe5p2bPkBmuoayza57jhCyWUBWd
    vaultTreasuryTokenBAccount: E3GHKwQbeJBgshptbeXEdSyRkAeiyaxqmSsfv3TLqcy9
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 7i4JAYu8GCGbFyiTrmjvJ68Q7WLN54y4r8F1KKdQRPma
    swapTokenMint: CrdocLxKTvPGHoi84krfsre3EcfcrHsgM9E2PFVGVGw4
    swapTokenAAccount: 2hZzp8EWjDPJzQS4jPRn4wt5fGJ2zpgaNRpBxFsymHHw
    swapTokenBAccount: H7ZiL93JPFPybAVrC74zPcwXrMkPRcADqAoHvMuPN92N
    swapFeeAccount: 51Wy5gKDKNngMQh5hxELmku4H8JeUwXcdKpbL2LbssX
    swapAuthority: J8e8N6V531nnRPzdiQTcneyeyv5AcVqrxQhHCiQKkQo6
    swap: APeTSKEryyKNYXc5ZHBtzNJhX4eLTBN9toQbL3sXVGCm
