environment: DEVNET
triggerDCA:
  - vault: ktC88rcBJ6T22jqWfuQ38RUgUrt6AQ3eRiDuoeGCo3n
    vaultProtoConfig: Fke6PnhUsjrY2wALcdTrNNVajgTRTLqrknfPcWaWjypL
    vaultTokenAAccount: 3LC4WR8bJ5M55XBxekRLjvaFcaCTwg3YoewYxLKmokqb
    vaultTokenBAccount: DwCGHoXzn7RoVcti8pmdK92iYV1J9sjYPWX7KRQuDC7C
    tokenAMint: 72HBqn7K1wu6dbxY3L9FNe6aLetwN9KfmB4RFDPR14Y3
    tokenBMint: BACh99A1k6vSoCYZFvFaZ637Dk3hm9XDAr5fAZSVktst
    swapTokenMint: 8Com5s5u4Bpo5gnejnAvhgyNCZLSPDvGYeZdUen2ZYjk
    swapTokenAAccount: HFfRYpgcrXgtQFpwXjk1y2DGQzddNmPmonahLBt6tZbt
    swapTokenBAccount: 7hxTyUyYSCsv3QmtabT2VFhyvbmFu3Yq43xn8m2fxXZb
    swapFeeAccount: 5GNb5u8VWwhvbTyv9AVvF73Egzk2VzR3PXknrixjwmct
    swapAuthority: 8knGHuXTJPTUuBmRNN6tDfpfYBVAAV8iWSkHXrqNbGPL
    swap: FoXCCt1dYSpuY6ixhQco59CvsTnVuE7YTVwXNaQhCzcH
