environment: DEVNET
triggerDCA:
  - vault: 6se7xmFSsWB1mWEgjSUsToa3Wsk47cyDFs4bukZUK3TR
    vaultProtoConfig: EtdpxLNA1mcb7ef5XDMN71QGiUb1h2yAcD5xBz3okhqp
    vaultTokenAAccount: 5jRAbcZMhJYfHRiFAzcghexWMwkTRQTjXFmpxkSbatqj
    vaultTokenBAccount: AuSgLSMDkbvXKDTpd1fhn2KFycWAUBL5mLj1XgsDwrTT
    vaultTreasuryTokenBAccount: GJy2jDPCCAZJgtKE7QjSMM5nNvMrih2XC3uP7wumqwir
    tokenAMint: 2tfR3MXUBzyfvrdzEiK26J7mpGhrzS1rRHe1owtinpxo
    tokenBMint: 8uCHB1gSPFg18dMmmSVhQ5HChAiAy66tdf8bZP4HtupH
    swapTokenMint: BNTkPDYGm5rL6YnzVM85oGwFZF4cMghasa3CVp348Tbv
    swapTokenAAccount: 5SbmTBWmZYBn6Y5T9w6buE5aQmpzDPTgavTj1fz1qFcX
    swapTokenBAccount: G3K9SMLp6p24dT9PdzigcZR9dHYZ2km8V24bQrqG4qN8
    swapFeeAccount: AV2HQSFrmviR3Yx7qPonXzmUy3re2hsEd8A7bCCCtGmD
    swapAuthority: DzYiL4enuTJyuW1hy6wAxpreog4KghVYbGKhJoaxGMYK
    swap: GpR9u1PkVKUKhCG52BGPbs8K25ksfXwaRTcQmdjco5Lr
