name: Test
on:
  pull_request:
  push: { branches: main }

jobs:
  build:
    name: Build keeper-bot
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: build
      run: go build cmd/main.go 

  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    # - name: Prepare
    #   id: prep
    #   run: |
    #     TAG=$(echo $GITHUB_SHA | head -c7)
    #     IMAGE="keeper_bot_test_image"
    #     echo ::set-output name=tagged_image::${IMAGE}:${TAG}
    #     echo ::set-output name=tag::${TAG}
  
    # - name: Set up Docker Buildx
    #   id: buildx        
    #   uses: docker/setup-buildx-action@master

    # - name: Cache Docker layers
    #   uses: actions/cache@v2
    #   with:
    #     path: /tmp/.buildx-cache
    #     key: ${{ runner.os }}-single-buildx-${{ github.sha }}
    #     restore-keys: |
    #       ${{ runner.os }}-single-buildx
  
    # - name: Build test image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     builder: ${{ steps.buildx.outputs.name }}
    #     file: ./build/githubactions/dockerfile
    #     load: true
    #     push: false # This would be set to true in a real world deployment scenario.
    #     tags: ${{ steps.prep.outputs.tagged_image }}
    #     cache-from: type=local,src=/tmp/.buildx-cache
    #     cache-to: type=local,dest=/tmp/.buildx-cache-new
  
    - name: Run solana-test-validator
      run: docker-compose --file ./build/githubactions/docker-compose.yaml up -d 
      # docker run --rm -p 8899:8899 solanalabs/solana:v1.8.5 -d

    - name: Run unit tests
      run: go test -coverprofile ./c.out $(go list ./...) || exit $?

    - name: Stop solana-test-validator
      run: docker-compose --file ./build/githubactions/docker-compose.yaml down 
    # # https://github.com/docker/build-push-action/issues/252
    # # https://github.com/moby/buildkit/issues/1896
    # - name: Move cache
    #   run: |
    #     rm -rf /tmp/.buildx-cache
    #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache